Repository artsy/metaphysics, pull requests merged in 2018-10, with the labels that each got.

#1322 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1329 Remove Kaws from being behind an env var flag
  .env.example
  src/config.ts
  src/lib/stitching/mergeSchemas.ts
Labels: Merge On Green

#1330 Dumping a schema first applies the example env vars, then your own
  package.json
  scripts/dump-schema.ts
Labels: Merge On Green

#1332 @damassi => Expose min and max price in cents for an artwork
  _schema.graphql
  src/schema/artwork/__tests__/artwork.test.js
  src/schema/artwork/index.ts
Labels: Merge On Green

#1328 Add oneTimeUse to CreateCreditCard mutation
  _schema.graphql
  src/schema/me/__tests__/create_credit_card_mutation.test.js
  src/schema/me/create_credit_card_mutation.js
Labels: Merge On Green

#1338 @sweir27 => Remove random shuffling of hero units
  src/schema/home/home_page_hero_units.js
Labels: Merge On Green

#1336 Cap pagination results to 100
  src/schema/fields/__tests__/pagination.test.js
  src/schema/fields/pagination.js
Labels: Merge On Green

#1340 fix null internation shipping for works with free domestic only shipping
  src/schema/artwork/__tests__/artwork.test.js
  src/schema/artwork/index.ts
Labels: Jira Synced

#1343 Expand OrderSortMethodEnum to sort over state_expires_at
  _schema.graphql
  src/data/exchange.graphql
  src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
  src/schema/ecommerce/types/orders_sort_method_enum.ts
Labels: Jira Synced

#1348 The hasNextPage flag should be false on page=100 when pagination results are capped to 100
  src/schema/__tests__/filter_artworks.test.js
  src/schema/fields/pagination.js
  src/schema/filter_artworks.js
Labels: Jira Synced, Merge On Green
