Repository artsy/metaphysics, pull requests merged in 2018-12, with the labels that each got.

#1412 Add buyerAcceptOffer after sync with Exchange
  _schema.graphql
  src/data/exchange.graphql
  src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
  src/schema/__tests__/ecommerce/buyer_accept_offer_mutation.test.ts
  src/schema/ecommerce/buyer_accept_offer_mutation.ts
  src/schema/schema.ts
Labels: Jira Synced

#1414 Expose Fair exhibitors in MP
  _schema.graphql
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced

#1416 [Artwork] Add missing `exclude` arg
  _schema.graphql
  src/schema/artist/index.ts
Labels: Merge On Green

#1403 [depth limit] Make it possible to disable this validation rule.
  src/config.ts
  src/index.ts
Labels: Jira Synced

#1421 Revert "DISCO-494: Return null shipping info if artwork is not acquirable"
  src/schema/artwork/__tests__/artwork.test.js
  src/schema/artwork/index.ts
Labels: Jira Synced

#1415 Add filtered artworks to Show, Fair
  _schema.graphql
  src/schema/__tests__/show.test.js
  src/schema/fair.ts
  src/schema/filter_artworks.ts
  src/schema/show.ts
Labels: Jira Synced

#1419 Expose stub shows for local discovery
  _schema.graphql
  src/schema/__tests__/city.test.ts
  src/schema/__tests__/show.test.js
  src/schema/city/index.ts
  src/schema/show.ts
Labels: Jira Synced

#1424 LD-85 Expose opening_reception_text on Show
  _schema.graphql
  src/schema/show.ts
Labels: Jira Synced

#1427 Refactor to fix bug in exposing Fair exhibitors
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced

#1426 Added default reject reasons to exchange
  src/data/exchange.graphql
  src/lib/stitching/exchange/__tests__/__snapshots__/schema.test.ts.snap
Labels: Jira Synced

#1420 Adds SellerCounterOfferOnOrderMutation
  _schema.graphql
  src/data/exchange.graphql
  src/schema/__tests__/ecommerce/seller_counter_offer_mutation.test.ts
  src/schema/ecommerce/seller_counter_offer_mutation.ts
  src/schema/schema.ts
Labels: Jira Synced

#1425 PLATFORM-959: Fix MP Excess Logging
  src/index.ts
  src/lib/HTTPError.ts
  src/lib/__tests__/graphqlErrorHandler.test.ts
  src/lib/apis/fetch.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/http_error.ts
  src/schema/partner_show.ts
  src/schema/show.ts
Labels: Jira Synced

#1430 Add artistsConnection to Fair
  _schema.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
  src/schema/sorts/fairArtistSorts.ts
Labels: Jira Synced

#1438 Add Show.counts.artists
  _schema.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/__tests__/show.test.js
  src/schema/show.ts
Labels: Jira Synced

#1442 Expose and structure artist insights from Gravity
  _schema.graphql
  src/schema/artist/__tests__/insights.test.ts
  src/schema/artist/index.ts
  src/schema/artist/insights.ts
Labels: Jira Synced

#1447 Adds offerable to artwork filters
  _schema.graphql
  src/schema/filter_artworks.ts
Labels: Merge On Green

#1449 @mzikherman => Update artwork pageview data
  src/data/weeklyArtworkPageviews.json
  src/schema/artwork/__tests__/artwork.test.js
Labels: Merge On Green

#1450 [Artwork#meta] Add new `share` field
  _schema.graphql
  src/schema/artwork/__tests__/meta.test.ts
  src/schema/artwork/index.ts
  src/schema/artwork/meta.ts
Labels: Jira Synced

#1448 Allow finding a local discovery city nearest to an arbitrary point
  _schema.graphql
  src/lib/__tests__/geospatial.test.ts
  src/lib/geospatial.ts
  src/schema/__tests__/city.test.ts
  src/schema/city/constants.ts
  src/schema/city/index.ts
Labels: Jira Synced, Merge On Green
