Repository artsy/metaphysics, pull requests merged in 2019-04, with the labels that each got.

#1645 Override 404ing missing_image.png asset reference
  src/schema/SearchableItem/SearchItemRawResponse.ts
  src/schema/SearchableItem/SearchableItemPresenter.ts
  src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
  src/schema/SearchableItem/index.ts
Labels: Jira Synced

#1643 Memoize query introspection during search query resolution
  src/schema/search/SearchResolver.ts
  src/schema/search/index.ts
Labels: Jira Synced, Merge On Green

#1642 Use custom date resolver for partner show events
  src/schema/__tests__/partner_show_events.test.ts
  src/schema/partner_show_event.ts
Labels: Jira Synced

#1649 Adds formattedOpeningHours to Fairs
  _schema.graphql
  src/lib/date.ts
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced

#1651 Partner operator shouldn't be able to access another partner's auctions
  src/schema/__tests__/causality_jwt.test.js
  src/schema/causality_jwt.ts
Labels: Jira Synced

#1657 [date] Fix tests breakage due to TZ ambiguity.
  src/lib/__tests__/date.test.ts
  src/lib/date.ts
Labels: Merge On Green

#1658 [test] Fix warnings about incorrect date format.
  src/lib/__tests__/date.test.ts
Labels: Merge On Green

#1656 Returns null for missing dates
  src/schema/fields/__tests__/date.test.js
  src/schema/fields/date.ts
Labels: Merge On Green

#1659 [tracer] Upgrade to latest DD and use upstream memcached plugin.
  package.json
  patches/dd-trace+0.7.3.patch
  src/lib/__tests__/cache.test.ts
  src/lib/cache.ts
  src/lib/loaders/__tests__/api-uncached.test.js
  src/lib/loaders/__tests__/api-uncached.test.ts
  src/lib/loaders/__tests__/api.test.ts
  src/lib/loaders/api/loader_without_authentication_factory.ts
  src/lib/rateLimiter.ts
  src/lib/tracer.ts
  yarn.lock
Labels: Jira Synced

#1662 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1664 Return credit card ID from buyer counter mutation
  src/schema/__tests__/ecommerce/buyer_counter_offer_mutation.test.ts
  src/schema/ecommerce/buyer_counter_offer_mutation.ts
Labels: Merge On Green

#1663 Add stiched artwrok to topArtworks
  _schema.graphql
  src/data/vortex.graphql
  src/lib/helpers.ts
  src/lib/loaders/loaders_without_authentication/vortex.ts
  src/lib/stitching/mergeSchemas.ts
  src/lib/stitching/vortex/__mocks__/link.ts
  src/lib/stitching/vortex/__tests__/topArtorks.test.ts
  src/lib/stitching/vortex/schema.ts
  src/lib/stitching/vortex/stitching.ts
  src/schema/partner.ts
Labels: Jira Synced

#1665 Use Eastern Time when formatting timestamps for auction search results
  src/schema/SearchableItem/SearchableItemPresenter.ts
  src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
Labels: Jira Synced

#1667 Fix location formatting in SearchableItemPresenter
  src/schema/SearchableItem/SearchableItemPresenter.ts
Labels: Merge On Green

#1670 Adds isBenefit and isGalleryAuction to sale schema
  _schema.graphql
  src/schema/sale/__tests__/index.test.js
  src/schema/sale/index.ts
Labels: Jira Synced

#1671 If an artworks category is OTHER, dont show a histogram for that artwork
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1674 Add appliedFiltersDisplay
  _schema.graphql
  src/lib/stitching/vortex/__mocks__/link.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1676 Fix case when there is no vortex context
  src/lib/stitching/vortex/stitching.ts
Labels: Merge On Green

#1684 Use sizeScore when fetching histogram
  src/data/vortex.graphql
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1688 Add renovate to metaphysics
  renovate.json
Labels: Merge On Green
