Repository artsy/metaphysics, pull requests merged in 2019-11, with the labels that each got.

#2033 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2031 [V2] Re-enable required root fields
  _schemaV2.graphql
  src/integration/__tests__/integration.test.ts
  src/schema/v2/Highlights/BroadCollectingGenes.ts
  src/schema/v2/Highlights/PopularArtists.ts
  src/schema/v2/Highlights/__tests__/BroadCollectingGenes.test.ts
  src/schema/v2/Highlights/__tests__/PopularArtists.test.ts
  src/schema/v2/Highlights/index.ts
  src/schema/v2/__tests__/artists.test.ts
  src/schema/v2/__tests__/genes.test.ts
  src/schema/v2/__tests__/suggested_genes.test.js
  src/schema/v2/__tests__/tag.test.js
  src/schema/v2/__tests__/tag.test.ts
  src/schema/v2/artists/__tests__/__snapshots__/popular.test.js.snap
  src/schema/v2/artworks.ts
  src/schema/v2/filterArtworksConnection.ts
  src/schema/v2/me/__tests__/follow_artist.test.js
  src/schema/v2/me/follow_artist.ts
  src/schema/v2/schema.ts
  src/schema/v2/tag.ts
  src/schema/v2/test/utils.ts
Labels: Jira Synced

#2034 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2035 [GROW-1621] update the Get the BMW Art Guide URL in city guide
  src/lib/sponsoredContent/data.json
Labels: Jira Synced

#2038 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2043 @mzikherman => [v2] Allow page to be specified by client
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#2044 Adds press release info for Paris Photo 2019
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green

#2039 Deploy
  _schema.graphql
  _schemaV2.graphql
  src/data/complete.queryMap.json
  src/lib/helpers.ts
  src/lib/sponsoredContent/data.json
  src/lib/stitching/kaws/stitching.ts
  src/lib/stitching/mergeSchemas.ts
  src/schema/v2/__tests__/search.test.ts
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/artist/shows.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/bidder.ts
  src/schema/v2/fields/pagination.ts
  src/schema/v2/filterArtworksConnection.ts
  src/schema/v2/gene.ts
  src/schema/v2/sale_artworks.ts
  src/schema/v2/schema.ts
  src/schema/v2/search/SearchResolver.ts
  src/schema/v2/user.ts
  src/test/utils.ts
Labels: Jira Synced

#2048 Remove v2 schema transforms
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
  src/schema/v2/home/__tests__/home_page_artist_module.test.js
  src/schema/v2/index.ts
  src/schema/v2/test/utils.ts
  src/schema/v2/v2/FilterFields.ts
  src/schema/v2/v2/RenameArguments.ts
  src/schema/v2/v2/RenameFields.ts
  src/schema/v2/v2/__tests__/RenameFields.test.ts
  src/schema/v2/v2/__tests__/v2.test.ts
  src/schema/v2/v2/index.ts
Labels: Merge On Green

#2061 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2062 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2065 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2067 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2074 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2075 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2076 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2077 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green
