Repository artsy/metaphysics, pull requests merged in 2019-02, with the labels that each got.

#1480 [package] Update dd-trace client to latest.
  package.json
  yarn.lock
Labels: Jira Synced

#1477 Add offer notes to offer mutations
  _schema.graphql
  src/data/exchange.graphql
  src/schema/__tests__/ecommerce/add_initial_offer_to_order_mutation.test.ts
  src/schema/__tests__/ecommerce/buyer_counter_offer_mutation.test.ts
  src/schema/__tests__/ecommerce/order_fields.ts
  src/schema/__tests__/ecommerce/seller_counter_offer_mutation.test.ts
  src/schema/ecommerce/query_helpers.ts
  src/schema/ecommerce/seller_counter_offer_mutation.ts
  src/schema/ecommerce/types/initial_offer_input_type.ts
  src/schema/ecommerce/types/offer.ts
  src/test/fixtures/exchange/offer_order.json
  src/test/fixtures/results/sample_order.js
Labels: Jira Synced

#1469 First pass resolver data batching
  .env.example
  src/config.ts
  src/lib/loaders/__tests__/batchLoader.test.ts
  src/lib/loaders/api/loader_interface.ts
  src/lib/loaders/batchLoader.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
Labels: Jira Synced

#1490 [package] Update dd-trace client to latest, again.
  package.json
  yarn.lock
Labels: Jira Synced

#1496 Debug dd trace client issue
  package.json
  patches/dd-trace+0.7.3.patch
  yarn.lock
Labels: Jira Synced

#1497 Adds is_followed to show
  _schema.graphql
  src/lib/loaders/__tests__/tracked_entity.test.js
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/loaders/loaders_with_authentication/tracked_entity.ts
  src/schema/__tests__/show.test.js
  src/schema/show.ts
Labels: Jira Synced

#1500 Support additional entity types during search
  _schema.graphql
  src/lib/loaders/searchLoader.ts
  src/schema/search/SearchEntity.ts
  src/schema/search/index.ts
Labels: Jira Synced

#1512 Set keyword_match_exact when keywords are set on a Kaws collection.
  _schema.graphql
  src/lib/stitching/kaws/__tests__/stitching.test.ts
  src/lib/stitching/kaws/stitching.ts
  src/schema/filter_artworks.ts
Labels: Jira Synced

#1518 Fixes fair booths being filtered out
  src/schema/__tests__/show.test.js
  src/schema/show.ts
Labels: Jira Synced

#1522 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1525 update kaws schema to include new randomize argument
  _schema.graphql
  src/data/kaws.graphql
  src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
Labels: Jira Synced

#1527 [City] Make fairs field a connection.
  _schema.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/__tests__/city.test.ts
  src/schema/__tests__/fairs.test.js
  src/schema/city/index.ts
  src/schema/fair.ts
  src/schema/fairs.ts
  src/schema/home/__tests__/home_page_fairs_module.test.js
  src/schema/home/fetch.ts
  src/schema/home/home_page_fairs_module.ts
  src/schema/home/results.ts
Labels: Jira Synced

#1534 Fix wrong artwork filtering on show page
  src/schema/__tests__/show.test.js
  src/schema/show.ts
Labels: Jira Synced, Merge On Green
