Repository artsy/metaphysics, pull requests merged in 2019-03, with the labels that each got.

#1533 Load all city shows and fairs
  src/lib/__tests__/all.test.ts
  src/lib/all.ts
  src/lib/helpers.ts
  src/lib/loaders/api/loader_interface.ts
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
  src/schema/fair.ts
  src/schema/partner_show.ts
  src/schema/sale/index.ts
  src/schema/sale_artworks.ts
  src/schema/show.ts
Labels: Jira Synced

#1536 Adds exhibition_period to Fairs
  _schema.graphql
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Merge On Green

#1539 Cache city shows and fairs for a day
  src/lib/all.ts
  src/lib/loaders/__tests__/api.test.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/api/loader_interface.ts
  src/lib/loaders/api/loader_with_authentication_factory.ts
  src/lib/loaders/api/loader_without_authentication_factory.ts
  src/lib/loaders/api/loader_without_cache_factory.ts
  src/lib/loaders/index.ts
  src/schema/__tests__/fair.test.js
  src/schema/city/index.ts
Labels: Jira Synced

#1547 Add static sponsored content
  _schema.graphql
  src/lib/sponsoredContent/data.json
  src/lib/sponsoredContent/index.ts
  src/schema/__tests__/city.test.ts
  src/schema/__tests__/fair.test.js
  src/schema/city/index.ts
  src/schema/fair.ts
Labels: Jira Synced

#1554 updated copy from BMW press release
  src/lib/sponsoredContent/data.json
Labels: Jira Synced

#1557 LD-354 - Updates artGuideUrl to correct URL
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green

#1556 [allViaLoader] No longer need to fetch any content to get /shows count.
  src/lib/all.ts
  src/schema/city/index.ts
Labels: Jira Synced

#1559 Add partner-type filtering to city shows field
  _schema.graphql
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
Labels: Jira Synced

#1562 Add optional dayThreshold and new ClosingSoon status
  _schema.graphql
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
  src/schema/input_fields/event_status.ts
Labels: Jira Synced, Merge On Green

#1563 Include manually curated shows in per-city sponsored content
  _schema.graphql
  src/lib/sponsoredContent/data.json
  src/lib/sponsoredContent/index.ts
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
Labels: Jira Synced

#1566 [City] Sort city data for consumption by Emission.
  src/schema/__tests__/city.test.ts
  src/schema/city/cityDataSortedByDisplayPreference.json
  src/schema/city/index.ts
Labels: Jira Synced

#1567 Update emission querymap JSON #trivial
  src/data/complete.queryMap.json
Labels: Jira Synced

#1553 Display DaySchedule union
  _schema.graphql
  src/schema/location.ts
Labels: Jira Synced, Merge On Green

#1570 Ensure non-stub sponsored shows follow normal displayable rules
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
Labels: Jira Synced, Merge On Green

#1569 Add support for PARTNER_ASC sort option for partner_shows
  _schema.graphql
  src/schema/sorts/partner_show_sorts.ts
Labels: Jira Synced

#1574 BMW art guide copy change for HK
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green

#1573 Add optional `city` argument to me.followsAndSaves.shows
  _schema.graphql
  src/schema/me/followed_shows.ts
Labels: Jira Synced

#1577 Passes sort and status to city followed shows
  _schema.graphql
  src/data/complete.queryMap.json
  src/schema/me/followed_shows.ts
Labels: Merge On Green

#1578 Associate staging sponsored show data for QA
  src/lib/sponsoredContent/data.json
Labels: Merge On Green

#1579 Associate sponsored show data in production
  src/lib/sponsoredContent/data.json
Labels: Merge On Green

#1582 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1585 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1587 Add new running_and_upcoming status
  _schema.graphql
  src/schema/input_fields/event_status.ts
Labels: Merge On Green

#1591 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1590 LD-304 - Updates date exhibitionPeriod format
  src/lib/__tests__/date.test.ts
  src/lib/date.ts
Labels: Jira Synced

#1594 Fix static data for sponsored shows
  src/lib/sponsoredContent/data.json
Labels: Merge On Green

#1595 Nudge Hong Kong for LD
  src/schema/city/cityDataSortedByDisplayPreference.json
Labels: Merge On Green

#1596 Do not filter out stub shows from show query
  src/schema/__tests__/show.test.js
  src/schema/show.ts
Labels: Jira Synced

#1601 Expose an isActive flag on Fair
  _schema.graphql
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced

#1603 Expose pressReleaseUrl on Show
  _schema.graphql
  src/schema/show.ts
Labels: Merge On Green

#1604 Exclude shows that were blocked from discovery
  src/schema/__tests__/city.test.ts
  src/schema/city/index.ts
Labels: Jira Synced

#1610 Pre-launch updates to hard-coded sponsored shows
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green

#1612 @mzikherman => [Autosuggest] Properly exclude shows from default entities
  src/schema/search/SearchEntity.ts
Labels: Merge On Green

#1616 More show changes from sponsor
  src/lib/sponsoredContent/data.json
Labels: Merge On Green

#1620 LD-526 - isActive now shows past Fairs
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced, Merge On Green

#1618 Vortex histogram hookup
  _schema.graphql
  src/data/vortex.graphql
  src/lib/loaders/loaders_with_authentication/index.ts
  src/lib/loaders/loaders_with_authentication/vortex.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/lib/loaders/loaders_without_authentication/vortex.ts
  src/lib/stitching/vortex/link.ts
  src/lib/stitching/vortex/schema.ts
  src/schema/analytics/PricingContext.ts
  src/schema/analytics/PricingContextType.ts
  src/schema/analytics/__tests__/PricingContext.test.ts
  src/schema/artwork/index.ts
Labels: Jira Synced

#1629 Real vortex stitching + Add money helper to histogram bin price fields
  _schema.graphql
  package.json
  src/lib/stitching/mergeSchemas.ts
  src/lib/stitching/vortex/__mocks__/link.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/schema.ts
  src/lib/stitching/vortex/stitching.ts
  src/schema/analytics/PricingContext.ts
  src/schema/analytics/PricingContextType.ts
  src/schema/analytics/__tests__/PricingContext.test.ts
  src/schema/artwork/index.ts
  src/schema/me/__tests__/recently_viewed_artworks.test.ts
  yarn.lock
Labels: Jira Synced

#1632 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1628 LD-538 - Fair shows pagination
  _schema.graphql
  src/schema/__tests__/fair.test.js
  src/schema/fair.ts
Labels: Jira Synced

#1625 Update descriptions for searchable item
  src/schema/SearchableItem/SearchableItemPresenter.ts
  src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
  src/schema/SearchableItem/index.ts
  src/schema/schema.ts
  src/schema/search/index.ts
  src/schema/searchableItem.ts
Labels: Jira Synced

#1637 Make sure list price is present for pricing context
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1638 Add SearchableItem description formatting for PartnerShow entity type
  _schema.graphql
  src/schema/SearchableItem/SearchItemRawResponse.ts
  src/schema/SearchableItem/SearchableItemPresenter.ts
  src/schema/SearchableItem/__tests__/SearchableItemPresenter.test.ts
  src/schema/SearchableItem/index.ts
Labels: Jira Synced
