Repository artsy/metaphysics, pull requests merged in 2019-05, with the labels that each got.

#1694 Update sponsored content text
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green

#1685 Gate pricingContext behind artist ID allow list [PURCHASE-1076]
  src/config.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1697 Sync vortex schema
  src/data/vortex.graphql
Labels: Merge On Green

#1703 Removes lab feature requirement for pricing context
  .env.example
  .env.test
  src/config.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/link.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1695 Switch to Apollo Server
  .env.example
  package.json
  src/config.ts
  src/extensions/errorExtension.ts
  src/extensions/loggingExtension.ts
  src/index.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/loaders/api/extensionsLogger.ts
  src/test/gql-server.js
  yarn.lock
Labels: Jira Synced, Merge On Green

#1707 Update persisted queries for Emission v1.11.0
  src/data/complete.queryMap.json
Labels: Merge On Green

#1696 'amount' helper should handle zero correctly [PURCHASE-995]
  src/schema/artwork/index.ts
  src/schema/fields/__tests__/money.test.ts
  src/schema/fields/money.ts
Labels: Jira Synced

#1710 Revert "Revert apollo server changes"
  .env.example
  package.json
  src/config.ts
  src/extensions/errorExtension.ts
  src/extensions/loggingExtension.ts
  src/index.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/loaders/api/extensionsLogger.ts
  src/test/gql-server.js
  yarn.lock
Labels: Merge On Green

#1711 Update Vortex schema with partner sales stats (GALL-1671)
  _schema.graphql
  src/data/vortex.graphql
Labels: Jira Synced

#1716 Deploy
  .circleci/config.yml
  README.md
  _schema.graphql
  src/data/vortex.graphql
Labels: Jira Synced

#1678 [V2] ID transformations and new endpoint
  .prettierignore
  _schema.graphql
  package.json
  patches/graphql+0.13.2.patch
  patches/graphql-tools+4.0.4.patch
  peril/upstreamSchemaValidator.ts
  src/index.ts
  src/schema/artist/insights.ts
  src/schema/artwork/attributionClass.ts
  src/schema/artwork_version.ts
  src/schema/ecommerce/types/offer.ts
  src/schema/ecommerce/types/order.ts
  src/schema/ecommerce/types/order_fulfillment.ts
  src/schema/ecommerce/types/order_line_item.ts
  src/schema/ecommerce/types/order_or_error_union.ts
  src/schema/fair.ts
  src/schema/featured_link.ts
  src/schema/gene_family.ts
  src/schema/home/params.ts
  src/schema/image/index.ts
  src/schema/index.ts
  src/schema/index_v2.ts
  src/schema/me/artwork_inquiries.ts
  src/schema/me/consignments/asset.ts
  src/schema/me/consignments/submission.ts
  src/schema/me/consignments/update_submission_mutation.ts
  src/schema/me/conversation/attachment.ts
  src/schema/me/conversation/delivery.ts
  src/schema/me/conversation/index.ts
  src/schema/me/conversation/message.ts
  src/schema/object_identification.ts
  src/schema/partner.ts
  src/schema/sale_artwork.ts
  src/schema/user.ts
  yarn.lock
Labels: Jira Synced

#1718 GALL-1753: Add order response time to Vortex schema
  _schema.graphql
  src/data/vortex.graphql
Labels: Merge On Green

#1719 [PURCHASE-1127] Switch to artist.disablePriceContext for returning pricing context data
  _schema.graphql
  src/config.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/stitching.ts
  src/schema/artist/index.ts
Labels: Jira Synced

#1717 Expose formatted total fields for partner sales stats (GALL-1671)
  _schema.graphql
  src/lib/stitching/vortex/__mocks__/link.ts
  src/lib/stitching/vortex/__tests__/partnerStatsSales.test.ts
  src/lib/stitching/vortex/__tests__/topArtworks.test.ts
  src/lib/stitching/vortex/stitching.ts
Labels: Jira Synced

#1727 Going for a deploy...
  .circleci/config.yml
  .prettierignore
  _schema.graphql
  package.json
  patches/graphql+0.13.2.patch
  patches/graphql-tools+4.0.4.patch
  peril/upstreamSchemaValidator.ts
  src/config.ts
  src/data/vortex.graphql
  src/index.ts
  src/lib/__tests__/crunchInterceptor.test.ts
  src/lib/crunchInterceptor.ts
  src/lib/stitching/vortex/__mocks__/link.ts
  src/lib/stitching/vortex/__tests__/partnerStatsSales.test.ts
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/lib/stitching/vortex/__tests__/topArtworks.test.ts
  src/lib/stitching/vortex/stitching.ts
  src/schema/artist/index.ts
  src/schema/artist/insights.ts
  src/schema/artwork/attributionClass.ts
  src/schema/artwork_version.ts
  src/schema/ecommerce/types/offer.ts
  src/schema/ecommerce/types/order.ts
  src/schema/ecommerce/types/order_fulfillment.ts
  src/schema/ecommerce/types/order_line_item.ts
  src/schema/ecommerce/types/order_or_error_union.ts
  src/schema/fair.ts
  src/schema/featured_link.ts
  src/schema/gene_family.ts
  src/schema/home/params.ts
  src/schema/image/index.ts
  src/schema/index.ts
  src/schema/index_v2.ts
  src/schema/me/artwork_inquiries.ts
  src/schema/me/consignments/asset.ts
  src/schema/me/consignments/submission.ts
  src/schema/me/consignments/update_submission_mutation.ts
  src/schema/me/conversation/attachment.ts
  src/schema/me/conversation/delivery.ts
  src/schema/me/conversation/index.ts
  src/schema/me/conversation/message.ts
  src/schema/object_identification.ts
  src/schema/partner.ts
  src/schema/sale_artwork.ts
  src/schema/user.ts
  src/test/interceptor.js
  yarn.lock
Labels: Jira Synced

#1735 Update schema for order count from Vortex (GALL-1503)
  _schema.graphql
  _schemaV2.graphql
  src/data/vortex.graphql
Labels: Jira Synced
