Repository artsy/metaphysics, pull requests merged in 2019-09, with the labels that each got.

#1920 [v2] Disable all root fields unused by Emission.
  _schemaV2.graphql
  src/schema/v2/__tests__/article.test.js
  src/schema/v2/__tests__/articles.test.js
  src/schema/v2/__tests__/artists.test.js
  src/schema/v2/__tests__/causality_jwt.test.js
  src/schema/v2/__tests__/collection.test.js
  src/schema/v2/__tests__/credit_card.test.ts
  src/schema/v2/__tests__/filterArtworksConnection.test.js
  src/schema/v2/__tests__/gene_families.test.js
  src/schema/v2/__tests__/genes.test.js
  src/schema/v2/__tests__/object_identification.test.js
  src/schema/v2/__tests__/ordered_set.test.js
  src/schema/v2/__tests__/ordered_sets.test.js
  src/schema/v2/__tests__/partner.test.js
  src/schema/v2/__tests__/partners.test.js
  src/schema/v2/__tests__/profile.test.js
  src/schema/v2/__tests__/suggested_genes.test.js
  src/schema/v2/__tests__/user.test.js
  src/schema/v2/__tests__/users.test.js
  src/schema/v2/artists/__tests__/popular.test.js
  src/schema/v2/artists/__tests__/trending.test.js
  src/schema/v2/artwork_version.ts
  src/schema/v2/match/__tests__/gene.test.js
  src/schema/v2/schema.ts
  src/schema/v2/system/__tests__/time.test.js
Labels: Jira Synced

#1922 [v2] Move services into System
  _schemaV2.graphql
  src/schema/v2/schema.ts
  src/schema/v2/system/index.ts
  src/schema/v2/system/services/convection.ts
  src/schema/v2/system/services/index.ts
  src/schema/v2/system/services/metaphysics.ts
Labels: Merge On Green

#1924 [v2] Cleanup suggested artists
  _schemaV2.graphql
  src/schema/v2/artist/related.ts
  src/schema/v2/me/__tests__/__snapshots__/suggested_artists.test.js.snap
  src/schema/v2/me/__tests__/follow_artist.test.js
  src/schema/v2/me/__tests__/suggested_artists.test.js
  src/schema/v2/me/follow_artist.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/suggested_artists.ts
  src/schema/v2/me/suggested_artists_args.ts
Labels: Jira Synced, Merge On Green

#1918 [GALL-1627] Partner loader query fix for partner analytics
  src/lib/helpers.ts
  src/lib/stitching/vortex/__tests__/rankedStats.test.ts
  src/schema/v1/collection.ts
  src/schema/v1/gene.ts
  src/schema/v1/me/index.ts
  src/schema/v1/partner.ts
  src/schema/v1/tag.ts
  src/schema/v2/collection.ts
  src/schema/v2/gene.ts
  src/schema/v2/me/index.ts
  src/schema/v2/partner.ts
  src/schema/v2/tag.ts
  src/test/utils.ts
Labels: Jira Synced

#1926 Deploy
  _schemaV2.graphql
  package.json
  src/lib/helpers.ts
  src/lib/stitching/vortex/__tests__/rankedStats.test.ts
  src/schema/v1/collection.ts
  src/schema/v1/gene.ts
  src/schema/v1/me/index.ts
  src/schema/v1/partner.ts
  src/schema/v1/tag.ts
  src/schema/v2/artist/related.ts
  src/schema/v2/collection.ts
  src/schema/v2/gene.ts
  src/schema/v2/me/__tests__/__snapshots__/suggested_artists.test.js.snap
  src/schema/v2/me/__tests__/follow_artist.test.js
  src/schema/v2/me/__tests__/suggested_artists.test.js
  src/schema/v2/me/follow_artist.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/suggested_artists.ts
  src/schema/v2/me/suggested_artists_args.ts
  src/schema/v2/partner.ts
  src/schema/v2/tag.ts
  src/test/utils.ts
  yarn.lock
Labels: Jira Synced

#1927 [v2] Remove more root fields
  _schemaV2.graphql
  patches/@types/graphql-relay+0.4.9.patch
  patches/graphql-relay+0.5.4.patch
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/__tests__/sale_artwork_max_bid_env.test.js
  src/schema/v2/__tests__/sale_artworks.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/match/__tests__/artist.test.js
  src/schema/v2/me/__tests__/sale_registrations.test.js
  src/schema/v2/me/followed_fairs.ts
  src/schema/v2/me/followed_shows.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/sale_registrations.ts
  src/schema/v2/object_identification.ts
  src/schema/v2/partner_artist.ts
  src/schema/v2/sale_artwork.ts
  src/schema/v2/sale_artworks.ts
  src/schema/v2/sales.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#1934 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1933 @alloy => [Directive] Implement a canonicalResource directive
  _schema.graphql
  _schemaV2.graphql
  package.json
  patches/graphql-tools+4.0.5.patch
  src/extensions/principalFieldDirectiveExtension.ts
  src/index.ts
  src/lib/__tests__/getPrincipalFieldDirectivePath.test.ts
  src/lib/getPrincipalFieldDirectivePath.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/stitching/mergeSchemas.ts
  src/schema/v1/__tests__/principalFieldDirective.test.ts
  src/schema/v1/schema.ts
  src/schema/v2/schema.ts
  src/schema/v2/v2/__tests__/v2.test.ts
  src/validations/__tests__/principalFieldDirectiveValidation.test.ts
  src/validations/principalFieldDirectiveValidation.ts
  yarn.lock
Labels: Merge On Green

#1935 @alloy => [Directive] Dont overwrite specified directives
  src/schema/v1/schema.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#1937 Revert "@alloy => [Package] Upgrade graphql to v14, and express-graphql to v0.9"
  .yarnclean
  package.json
  patches/graphql+0.13.2.patch
  patches/graphql+14.5.4.patch
  src/lib/__tests__/graphqlTimeoutMiddleware.test.ts
  src/lib/deprecation.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/graphqlTimeoutMiddleware.ts
  src/lib/stitching/exchange/transformers/replaceCommerceDateTimeType.ts
  src/schema/v1/__tests__/sale_artwork.test.js
  src/schema/v1/article.ts
  src/schema/v1/artist/shows.ts
  src/schema/v1/artists/trending.ts
  src/schema/v1/artwork/context.ts
  src/schema/v1/artwork/highlight.ts
  src/schema/v1/ecommerce/types/order_party_union.ts
  src/schema/v1/external_partner.ts
  src/schema/v1/featured_link.ts
  src/schema/v1/filter_artworks.ts
  src/schema/v1/gene.ts
  src/schema/v1/gene_families.ts
  src/schema/v1/gene_family.ts
  src/schema/v1/home/context.ts
  src/schema/v1/item.ts
  src/schema/v1/me/follow_artists.ts
  src/schema/v1/me/followed_fairs.ts
  src/schema/v1/partner.ts
  src/schema/v1/partner_artist.ts
  src/schema/v1/partner_show.ts
  src/schema/v1/sale/index.ts
  src/schema/v1/show.ts
  src/schema/v1/tag.ts
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/ecommerce/types/order_party_union.ts
  src/schema/v2/external_partner.ts
  src/schema/v2/gene.ts
  src/schema/v2/gene_families.ts
  src/schema/v2/gene_family.ts
  src/schema/v2/me/followed_fairs.ts
  src/schema/v2/partner.ts
  src/schema/v2/partner_artist.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/show.ts
  src/schema/v2/v2/RenameFields.ts
  yarn.lock
Labels: Merge On Green

#1943 @anandaroop => [Patch] Dont coerce variables when there are none
  patches/express-graphql+0.9.0.patch
Labels: Jira Synced, Merge On Green

#1941 PURCHASE-1471, PURCHASE-1468, 1476: Updates to inquiry fees description, shippingInfo returns non-country specific strings, new fields added related to shipping
  _schema.graphql
  _schemaV2.graphql
  src/schema/v1/artwork/__tests__/artwork.test.js
  src/schema/v1/artwork/index.ts
  src/schema/v1/fields/money.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/fields/money.ts
Labels: Jira Synced

#1946 @alloy => Downgrade graphql-js libs and remove patches
  .yarnclean
  package.json
  patches/express-graphql+0.9.0.patch
  patches/graphql+0.13.2.patch
  patches/graphql+14.5.4.patch
  src/lib/__tests__/graphqlTimeoutMiddleware.test.ts
  src/lib/deprecation.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/graphqlTimeoutMiddleware.ts
  src/lib/stitching/exchange/transformers/replaceCommerceDateTimeType.ts
  src/schema/v1/__tests__/sale_artwork.test.js
  src/schema/v1/article.ts
  src/schema/v1/artist/shows.ts
  src/schema/v1/artists/trending.ts
  src/schema/v1/artwork/context.ts
  src/schema/v1/artwork/highlight.ts
  src/schema/v1/ecommerce/types/order_party_union.ts
  src/schema/v1/external_partner.ts
  src/schema/v1/featured_link.ts
  src/schema/v1/filter_artworks.ts
  src/schema/v1/gene.ts
  src/schema/v1/gene_families.ts
  src/schema/v1/gene_family.ts
  src/schema/v1/home/context.ts
  src/schema/v1/item.ts
  src/schema/v1/me/follow_artists.ts
  src/schema/v1/me/followed_fairs.ts
  src/schema/v1/partner.ts
  src/schema/v1/partner_artist.ts
  src/schema/v1/partner_show.ts
  src/schema/v1/sale/index.ts
  src/schema/v1/show.ts
  src/schema/v1/tag.ts
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/ecommerce/types/order_party_union.ts
  src/schema/v2/external_partner.ts
  src/schema/v2/gene.ts
  src/schema/v2/gene_families.ts
  src/schema/v2/gene_family.ts
  src/schema/v2/me/followed_fairs.ts
  src/schema/v2/partner.ts
  src/schema/v2/partner_artist.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/show.ts
  src/schema/v2/v2/RenameFields.ts
  yarn.lock
Labels: Merge On Green

#1938 Deploy
  .circleci/config.yml
  .yarnclean
  _schema.graphql
  _schemaV2.graphql
  package.json
  patches/graphql+0.13.2.patch
  patches/graphql+14.5.4.patch
  scripts/schema-drift.ts
  src/integration/__tests__/integration.test.ts
  src/lib/__tests__/graphqlTimeoutMiddleware.test.ts
  src/lib/deprecation.ts
  src/lib/graphqlErrorHandler.ts
  src/lib/graphqlTimeoutMiddleware.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/exchange/transformers/replaceCommerceDateTimeType.ts
  src/schema/v1/__tests__/sale_artwork.test.js
  src/schema/v1/article.ts
  src/schema/v1/artist/shows.ts
  src/schema/v1/artists/trending.ts
  src/schema/v1/artwork/__tests__/artwork.test.js
  src/schema/v1/artwork/context.ts
  src/schema/v1/artwork/highlight.ts
  src/schema/v1/artwork/index.ts
  src/schema/v1/ecommerce/types/order_party_union.ts
  src/schema/v1/external_partner.ts
  src/schema/v1/featured_link.ts
  src/schema/v1/fields/money.ts
  src/schema/v1/filter_artworks.ts
  src/schema/v1/gene.ts
  src/schema/v1/gene_families.ts
  src/schema/v1/gene_family.ts
  src/schema/v1/home/context.ts
  src/schema/v1/item.ts
  src/schema/v1/me/follow_artists.ts
  src/schema/v1/me/followed_fairs.ts
  src/schema/v1/partner.ts
  src/schema/v1/partner_artist.ts
  src/schema/v1/partner_show.ts
  src/schema/v1/sale/index.ts
  src/schema/v1/show.ts
  src/schema/v1/tag.ts
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/ecommerce/types/order_party_union.ts
  src/schema/v2/external_partner.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/gene.ts
  src/schema/v2/gene_families.ts
  src/schema/v2/gene_family.ts
  src/schema/v2/me/followed_fairs.ts
  src/schema/v2/partner.ts
  src/schema/v2/partner_artist.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/sales.ts
  src/schema/v2/show.ts
  src/schema/v2/v2/RenameFields.ts
  yarn.lock
Labels: Jira Synced

#1949 @damassi => [Extensions] Make sure not to send unnecessary empty extensions object
  src/index.ts
  src/integration/__tests__/integration.test.ts
Labels: Merge On Green

#1952 Add Bidder query
  _schema.graphql
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v1/bidder.ts
  src/schema/v1/me/__tests__/bidders.test.js
  src/schema/v1/me/__tests__/create_bidder_mutation.test.js
  src/schema/v2/__tests__/bidder.test.js
  src/schema/v2/bidder.ts
  src/schema/v2/me/__tests__/create_bidder_mutation.test.js
  src/schema/v2/object_identification.ts
Labels: Merge On Green

#1957 PURCHASE-1497: additionalInformation is null
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#1966 Add time_zone/timeZone to Sale
  _schema.graphql
  _schemaV2.graphql
  src/schema/v1/sale/__tests__/index.test.js
  src/schema/v1/sale/index.ts
  src/schema/v2/sale/__tests__/index.test.js
  src/schema/v2/sale/index.ts
Labels: Jira Synced

#1970 Update emission querymap JSON
  src/data/complete.queryMap.json
Labels: Merge On Green

#1972 Adds StaticContent
  _schema.graphql
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v1/schema.ts
  src/schema/v1/static_content.ts
  src/schema/v2/schema.ts
  src/schema/v2/static_content.ts
Labels: Merge On Green

#1974 [City Guide] Add sponsored content for Frieze London 2019
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Merge On Green
