Repository artsy/metaphysics, pull requests merged in 2020-05, with the labels that each got.

#2343 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2344 Deploy
  _schemaV2.graphql
  src/data/complete.queryMap.json
  src/schema/v2/artist/index.ts
  src/schema/v2/home/__tests__/home_page_artist_module.test.js
  src/schema/v2/home/__tests__/home_page_fairs_module.test.js
  src/schema/v2/home/home_page_artist_module.ts
  src/schema/v2/home/home_page_fairs_module.ts
Labels: Jira Synced

#2348 [Consignments] Update microfunnel spreadsheet
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments, Merge On Green

#2350 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2353 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2349 Deploy
  src/data/complete.queryMap.json
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments

#2355 Revert "Preserve empty array in query string"
  src/lib/__tests__/helpers.test.ts
  src/lib/helpers.ts
Labels: Merge On Green

#2359 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2362 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2366 [Consignments] Update spreadsheet
  src/schema/v2/artist/targetSupply/utils/__tests__/getMicrofunnelData.test.ts
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments, Merge On Green

#2363 Feature Type
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/Feature/Feature.ts
  src/schema/v2/Feature/FeatureImageType.ts
  src/schema/v2/Feature/FeatureImageVersionEnum.ts
  src/schema/v2/Feature/FeatureType.ts
  src/schema/v2/Feature/index.ts
  src/schema/v2/fields/markdown.ts
  src/schema/v2/image/cropped.ts
  src/schema/v2/image/proxies/embedly.ts
  src/schema/v2/image/proxies/gemini.ts
  src/schema/v2/image/proxies/index.ts
  src/schema/v2/image/resized.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#2367 Deploy
  .circleci/config.yml
  _schemaV2.graphql
  package.json
  src/lib/__tests__/helpers.test.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/stitching.ts
  src/lib/stitching/kaws/__tests__/stitching.test.ts
  src/lib/stitching/kaws/stitching.ts
  src/schema/v2/Feature/Feature.ts
  src/schema/v2/Feature/FeatureImageType.ts
  src/schema/v2/Feature/FeatureImageVersionEnum.ts
  src/schema/v2/Feature/FeatureType.ts
  src/schema/v2/Feature/index.ts
  src/schema/v2/artist/targetSupply/utils/__tests__/getMicrofunnelData.test.ts
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
  src/schema/v2/fields/markdown.ts
  src/schema/v2/home/homePageMarketingCollectionsModule.ts
  src/schema/v2/home/index.ts
  src/schema/v2/image/cropped.ts
  src/schema/v2/image/proxies/embedly.ts
  src/schema/v2/image/proxies/gemini.ts
  src/schema/v2/image/proxies/index.ts
  src/schema/v2/image/resized.ts
  src/schema/v2/schema.ts
  src/types/runtime/gravity/Artist.ts
  src/types/runtime/gravity/Artwork.ts
  src/types/runtime/gravity/CulturalMaker.ts
  src/types/runtime/gravity/EditionSet.ts
  src/types/runtime/gravity/Feature.ts
  src/types/runtime/gravity/Image.ts
  src/types/runtime/gravity/Partner.ts
  src/types/runtime/gravity/PartnerCategory.ts
  src/types/runtime/gravity/index.ts
  src/types/runtime/index.ts
  yarn.lock
Labels: Consignments, Jira Synced

#2372 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2374 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2375 Fixes for return value of setsLoader
  src/schema/v1/__tests__/ordered_sets.test.js
  src/schema/v1/ordered_sets.ts
  src/schema/v2/__tests__/ordered_sets.test.js
  src/schema/v2/ordered_sets.ts
Labels: Merge On Green

#2383 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2370 Deploy
  _schema.graphql
  _schemaV2.graphql
  index.js
  package.json
  src/data/complete.queryMap.json
  src/index.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/stitching.ts
  src/schema/v1/__tests__/ordered_sets.test.js
  src/schema/v1/ordered_sets.ts
  src/schema/v2/Feature/FeatureImageType.ts
  src/schema/v2/Feature/FeatureType.ts
  src/schema/v2/__tests__/ordered_sets.test.js
  src/schema/v2/fields/cached.ts
  src/schema/v2/home/home_page_sales_module.ts
  src/schema/v2/item.ts
  src/schema/v2/me/index.ts
  src/schema/v2/ordered_set.ts
  src/schema/v2/ordered_sets.ts
  src/types/runtime/gravity/Artwork.ts
  src/types/runtime/gravity/Feature.ts
  src/types/runtime/gravity/FeaturedLink.ts
  src/types/runtime/gravity/OrderedItem.ts
  src/types/runtime/gravity/OrderedSet.ts
  src/types/runtime/gravity/Sale.ts
  src/types/runtime/gravity/index.ts
  yarn.lock
Labels: Jira Synced

#2392 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2397 Exposes new fields on Feature and FeaturedLink
  _schemaV2.graphql
  src/schema/v2/Feature/FeatureType.ts
  src/schema/v2/featured_link.ts
  src/types/runtime/gravity/Feature.ts
  src/types/runtime/gravity/FeaturedLink.ts
Labels: Merge On Green

#2395 Make optional fields on viewing room nullable in graphql type
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Labels: Merge On Green

#2399 Supports Markdown on OrderedSets; generic ImageType on Features
  _schemaV2.graphql
  src/schema/v2/Feature/FeatureImageType.ts
  src/schema/v2/Feature/FeatureImageVersionEnum.ts
  src/schema/v2/Feature/FeatureType.ts
  src/schema/v2/__tests__/ordered_set.test.js
  src/schema/v2/featured_link.ts
  src/schema/v2/ordered_set.ts
Labels: Merge On Green

#2404 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2405 Run relay-compiler when updating emission/eigen
  scripts/push-schema-changes.js
Labels: Merge On Green

#2407 Fix viewing rooms not filtered by partner id
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/stitching.ts
Labels: Merge On Green

#2403 Introduce `Me.canRequestEmailConfirmation`
  _schemaV2.graphql
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
Labels: Merge On Green

#2409 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2420 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2419 Deploy
  .babelrc
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/data/complete.queryMap.json
  src/schema/v1/index.ts
  src/schema/v2/__tests__/artworks.test.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artworks.ts
  src/schema/v2/index.ts
  yarn.lock
Labels: Jira Synced

#2418 [Consignments] Add artworksConnection to microfunnel & realizedPrice to Artwork
  _schemaV2.graphql
  package.json
  src/schema/v2/artist/targetSupply/__tests__/index.test.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artist/targetSupply/utils/getMicrofunnelData.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  yarn.lock
Labels: Consignments

#2422 Deploy
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/schema/v2/artist/targetSupply/__tests__/index.test.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artist/targetSupply/utils/getMicrofunnelData.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  yarn.lock
Labels: Consignments

#2424 [Toolchain] Push schema changes to force
  scripts/push-schema-changes.js
Labels: Merge On Green

#2426 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2425 Deploy
  _schema.graphql
  _schemaV2.graphql
  scripts/push-schema-changes.js
  src/data/complete.queryMap.json
  src/data/convection.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/schema/v2/filterArtworksConnection.ts
Labels: Jira Synced
