Repository artsy/metaphysics, pull requests merged in 2020-03, with the labels that each got.

#2215 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2217 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2218 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2220 Fixes a bug where lot condition report can not be enabled
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#2223 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2221 [Consignments] Reenable Convection Stitching
  _schema.graphql
  _schemaV2.graphql
  hokusai/test.yml
  package.json
  src/data/complete.queryMap.json
  src/data/convection.graphql
  src/schema/v1/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/submissions.test.js
  src/schema/v1/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/asset_uploads/__tests__/create_asset_request_mutation.test.js
  src/schema/v2/asset_uploads/__tests__/finalize_asset_mutation.test.js
  src/schema/v2/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/submissions.test.js
  src/schema/v2/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v2/me/consignments/create_submission_mutation.ts
  src/schema/v2/me/consignments/update_submission_mutation.ts
  src/schema/v2/schema.ts
Labels: Consignments

#2226 Sync Convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Merge On Green

#2227 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2224 Deploy
  _schema.graphql
  _schemaV2.graphql
  hokusai/test.yml
  package.json
  src/data/complete.queryMap.json
  src/data/convection.graphql
  src/schema/v1/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/submissions.test.js
  src/schema/v1/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/asset_uploads/__tests__/create_asset_request_mutation.test.js
  src/schema/v2/asset_uploads/__tests__/finalize_asset_mutation.test.js
  src/schema/v2/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/submissions.test.js
  src/schema/v2/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v2/me/consignments/create_submission_mutation.ts
  src/schema/v2/me/consignments/update_submission_mutation.ts
  src/schema/v2/schema.ts
Labels: Consignments

#2229 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2225 Enable fetching auction lot date ranges on auctions connection
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/diffusion.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/auction_result.ts
  src/schema/v2/types/yearRange.ts
Labels: Merge On Green

#2232 Update convection schema
  src/data/convection.graphql
Labels: Merge On Green

#2236 Update convection schema
  package.json
  scripts/dump-remote-schema.ts
  src/data/convection.graphql
Labels: Merge On Green

#2238 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2243 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2244 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2248 Update convection schema again
  src/data/convection.graphql
Labels: Merge On Green

#2250 Fix convection artist id mapping
  src/lib/stitching/convection/stitching.ts
Labels: Merge On Green

#2252 [Consignments] Delete unstitched code
  _schema.graphql
  _schemaV2.graphql
  src/schema/v1/me/__tests__/consignments/__snapshots__/add_asset_to_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/create_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/update_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/submissions.test.js
  src/schema/v1/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v1/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v1/me/consignments/asset.ts
  src/schema/v1/me/consignments/create_submission_mutation.ts
  src/schema/v1/me/consignments/submission.ts
  src/schema/v1/me/consignments/submissions.ts
  src/schema/v1/me/consignments/update_submission_mutation.ts
  src/schema/v1/me/index.ts
  src/schema/v1/schema.ts
  src/schema/v2/me/__tests__/consignments/__snapshots__/add_asset_to_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/create_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/update_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/submissions.test.js
  src/schema/v2/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v2/me/consignments/asset.ts
  src/schema/v2/me/consignments/create_submission_mutation.ts
  src/schema/v2/me/consignments/submission.ts
  src/schema/v2/me/consignments/submissions.ts
  src/schema/v2/me/consignments/update_submission_mutation.ts
  src/schema/v2/me/index.ts
Labels: Consignments

#2253 Deploy
  _schema.graphql
  _schemaV2.graphql
  src/schema/v1/me/__tests__/consignments/__snapshots__/add_asset_to_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/create_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
  src/schema/v1/me/__tests__/consignments/__snapshots__/update_submission_mutation.test.js.snap
  src/schema/v1/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v1/me/__tests__/consignments/submissions.test.js
  src/schema/v1/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v1/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v1/me/consignments/asset.ts
  src/schema/v1/me/consignments/create_submission_mutation.ts
  src/schema/v1/me/consignments/submission.ts
  src/schema/v1/me/consignments/submissions.ts
  src/schema/v1/me/consignments/update_submission_mutation.ts
  src/schema/v1/me/index.ts
  src/schema/v1/schema.ts
  src/schema/v2/me/__tests__/consignments/__snapshots__/add_asset_to_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/create_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/submissions.test.js.snap
  src/schema/v2/me/__tests__/consignments/__snapshots__/update_submission_mutation.test.js.snap
  src/schema/v2/me/__tests__/consignments/add_asset_to_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/create_submission_mutation.test.js
  src/schema/v2/me/__tests__/consignments/submissions.test.js
  src/schema/v2/me/__tests__/consignments/update_submission_mutation.test.js
  src/schema/v2/me/consignments/add_asset_to_submission_mutation.ts
  src/schema/v2/me/consignments/asset.ts
  src/schema/v2/me/consignments/create_submission_mutation.ts
  src/schema/v2/me/consignments/submission.ts
  src/schema/v2/me/consignments/submissions.ts
  src/schema/v2/me/consignments/update_submission_mutation.ts
  src/schema/v2/me/index.ts
Labels: Consignments

#2254 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2256 Update emission query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2257 Update the convection schema
  src/data/convection.graphql
  src/lib/stitching/convection/schema.ts
Labels: Merge On Green

#2258 Update schema
  _schema.graphql
  _schemaV2.graphql
Labels: Merge On Green

#2260 [AUCT-962] Add identityVerified to me object
  _schemaV2.graphql
  src/schema/v2/me/__tests__/index.test.js
  src/schema/v2/me/index.ts
Labels: Merge On Green

#2261 Deploy
  _schemaV2.graphql
  src/schema/v2/me/__tests__/index.test.js
  src/schema/v2/me/index.ts
  src/schema/v2/sale/__tests__/index.test.js
  src/schema/v2/sale/index.ts
Labels: Jira Synced

#2264 Update convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Merge On Green

#2266 [Consignments] Add Artist.targetSupply field
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/targetSupply/__tests__/fixtures/artistMicrofunnelFixture.ts
  src/schema/v2/artist/targetSupply/__tests__/index.test.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artist/targetSupply/utils/__tests__/getMicrofunnelData.test.ts
  src/schema/v2/artist/targetSupply/utils/getMicrofunnelData.ts
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments

#2267 Deploy
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/targetSupply/__tests__/fixtures/artistMicrofunnelFixture.ts
  src/schema/v2/artist/targetSupply/__tests__/index.test.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artist/targetSupply/utils/__tests__/getMicrofunnelData.test.ts
  src/schema/v2/artist/targetSupply/utils/getMicrofunnelData.ts
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments
