Repository artsy/metaphysics, pull requests merged in 2020-12, with the labels that each got.

#2866 chore: Add provenance to My Collection Artwork mutations
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Jira Synced

#2872 My bids - remove cents from formatted currencies
  src/lib/stitching/causality/__tests__/stitching.test.ts
  src/lib/stitching/causality/stitching.ts
Labels: Jira Synced

#2880 add stitched sellingPrice field
  _schema.graphql
  _schemaV2.graphql
  src/data/causality.graphql
  src/lib/stitching/causality/__tests__/stitching.test.ts
  src/lib/stitching/causality/stitching.ts
Labels: Jira Synced, Squash On Green

#2878 feat: add auction result type
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/diffusion.ts
  src/schema/v1/__tests__/auction_results.test.js
  src/schema/v1/artist/index.ts
  src/schema/v2/__tests__/auction_result.test.ts
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/auction_result.ts
  src/schema/v2/schema.ts
Labels: Squash On Green

#2897 feat(classifications): add new artwork classification (attribution class) values
  src/config.ts
  src/lib/attributionClasses.ts
  src/schema/v2/artworkAttributionClasses.ts
Labels: Jira Synced

#2900 feat(my collection): create/update edition information
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Squash On Green

#2885 Fix failed lotStandingConnection queries when a sale artwork is unpublished
  src/lib/stitching/causality/__tests__/stitching.test.ts
  src/lib/stitching/causality/stitching.ts
Labels: Jira Synced

#2911 chore: Expose email frequency reads and writes
  _schemaV2.graphql
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
Labels: Merge On Green
