Repository artsy/metaphysics, pull requests merged in 2020-06, with the labels that each got.

#2436 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2441 Update convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
  src/lib/stitching/convection/schema.ts
Labels: Merge On Green

#2448 Upgrade DataDog Library
  package.json
  patches/dd-trace+0.20.3.patch
  yarn.lock
Labels: Merge On Green

#2453 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2456 [Consignments] Update spreadsheet
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
Labels: Consignments, Merge On Green

#2457 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2458 Disables Apollo by default
  .env.oss
Labels: Merge On Green

#2454 Deploy
  .circleci/config.yml
  .env.oss
  _schemaV2.graphql
  src/data/complete.queryMap.json
  src/schema/v2/artist/targetSupply/utils/staticCSVToJSONData.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Consignments, Jira Synced

#2464 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2466 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2470 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2478 these just make copy paste harder
  README.md
Labels: Merge On Green

#2480 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2485 Revert "Change `formattedEndAt` format and add `formattedStartAt` [GALL-2988]"
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/index.ts
  src/lib/date.ts
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/stitching.ts
  src/schema/v1/fields/date.ts
  src/schema/v2/fields/date.ts
  yarn.lock
Labels: Jira Synced

#2476 Deploy
  .circleci/config.yml
  README.md
  _schema.graphql
  _schemaV2.graphql
  src/data/complete.queryMap.json
  src/data/gravity.graphql
  src/data/lewitt.graphql
  src/index.ts
  src/lib/loaders/loaders_with_authentication/impulse.ts
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/schema.ts
  src/schema/v1/me/__tests__/conversation/__snapshots__/conversation.test.js.snap
  src/schema/v1/me/__tests__/conversation/conversation.test.js
  src/schema/v1/me/conversation/invoice.ts
  src/schema/v1/me/conversation/message.ts
  src/schema/v2/me/__tests__/conversation/__snapshots__/conversation.test.js.snap
  src/schema/v2/me/__tests__/conversation/conversation.test.js
  src/schema/v2/me/conversation/invoice.ts
  src/schema/v2/me/conversation/message.ts
Labels: Jira Synced

#2488 Update hokusai required version
  hokusai/config.yml
Labels: Merge On Green

#2491 @dzucconi => [OrderedSets] Readd root type to V2 schema
  _schemaV2.graphql
  src/schema/v2/__tests__/ordered_sets.test.js
  src/schema/v2/ordered_sets.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#2493 Update eigen query map
  src/data/complete.queryMap.json
Labels: Merge On Green

#2499 Add Shows endpoint
  _schemaV2.graphql
  src/schema/v2/__tests__/shows.test.js
  src/schema/v2/schema.ts
  src/schema/v2/shows.ts
Labels: Merge On Green

#2496 Re-enable Partners root field, convert to connection
  _schemaV2.graphql
  src/schema/v2/__tests__/partners.test.js
  src/schema/v2/filter_partners.ts
  src/schema/v2/partner_category.ts
  src/schema/v2/partners.ts
  src/schema/v2/schema.ts
Labels: Merge On Green
