Repository artsy/metaphysics, pull requests merged in 2020-10, with the labels that each got.

#2744 Pend some time-bombs to unblock master branch
  src/schema/v1/__tests__/partner_show_events.test.ts
  src/schema/v2/__tests__/show_events.test.ts
Labels: Merge On Green

#2753 chore(FX-2340): Add sponsored content for Frieze London
  src/lib/sponsoredContent/data.json
Labels: Jira Synced, Squash On Green

#2754 Deploy
  src/lib/sponsoredContent/data.json
Labels: Jira Synced

#2760 feat: followed galleries
  _schemaV2.graphql
  src/schema/v2/me/__tests__/followed_galleries.test.ts
  src/schema/v2/me/followed_galleries.ts
  src/schema/v2/me/index.ts
Labels: Squash On Green

#2761 Update exchange schema
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
  src/lib/stitching/exchange/stitching.ts
Labels: Merge On Green

#2764 Add more images to my collection artworks
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Merge On Green

#2769 Fix mysterious schema drift
  _schemaV2.graphql
Labels: Merge On Green

#2784 Use basic endpoints to create/update My Collection artworks
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Merge On Green

#2790 @dzucconi => [Show] Stitch in viewingRoomsConnection
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/stitching.ts
  src/schema/v2/show.ts
Labels: Merge On Green

#2785 feat: Add `SubmitInquiryRequestMutation` for artwork inquiry
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/conversation/__snapshots__/submit_inquiry_request_mutation.test.ts.snap
  src/schema/v2/me/__tests__/conversation/submit_inquiry_request_mutation.test.ts
  src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#2795 fix: disable inquiryQuestions for non inquirable artworks
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#2800 fix: format displayTimeleyAt according to the user timeZone
  src/schema/v2/sale/__tests__/index.test.ts
  src/schema/v2/sale/display.ts
  src/schema/v2/sale/index.ts
Labels: Merge On Green

#2806 Ensure we don't try to parse details if they don't exist
  src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts
Labels: Merge On Green
