Repository artsy/metaphysics, pull requests merged in 2021-07, with the labels that each got.

#3263 fix: filter out auction results without artist id
  src/schema/v2/me/__tests__/auction_results_by_followed_artists.test.ts
  src/schema/v2/me/auction_results_by_followed_artists.ts
Labels: Jira Synced

#3273 feat(shows): adds filter for event status
  _schemaV2.graphql
  src/schema/v2/shows.ts
Labels: Squash On Green

#3275 fix(show): returns total count for artworks connection
  src/schema/v2/show.ts
Labels: Squash On Green

#3261 feat: show only for_sale artworks on "similar grid"
  src/schema/v2/home/results.ts
Labels: Jira Synced

#3276 Update home screen titles
  src/schema/v2/home/__tests__/home_page_artwork_module.test.js
  src/schema/v2/home/title.ts
Labels: Jira Synced, Squash On Green

#3288 bugfix: Fix duplicate items in MyBids component
  src/schema/v2/me/myBids.ts
Labels: Squash On Green

#3293 fix: fetch more than the first page
  _schemaV2.graphql
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/fair.ts
Labels: Squash On Green

#3295 Deploy
  src/schema/v2/fair.ts
  src/schema/v2/partner.ts
Labels: Jira Synced

#3300 toolchain: Match setup script with force
  Brewfile
  README.md
  package.json
  scripts/setup.sh
Labels: Squash On Green
