Repository artsy/metaphysics, pull requests merged in 2021-08, with the labels that each got.

#3320 feat: add articlesConnection to FairOrganizer type
  _schemaV2.graphql
  src/schema/v2/fair_organizer.ts
Labels: Jira Synced

#3319 fix: failed changelog parser checking on Eigen
  scripts/push-schema-changes.js
Labels: Squash On Green

#3333 chore: Bump Update Repo
  package.json
  yarn.lock
Labels: Merge On Green

#3338 fix: Fix Python Installation Path
  .circleci/config.yml
Labels: Squash On Green

#3337 feature: Add include variable to artworkModules field
  src/schema/v2/home/__tests__/home_page_artwork_modules.test.js
  src/schema/v2/home/home_page_artwork_modules.ts
Labels: Jira Synced

#3326 feat: allow clients to fetch a secured public API key for Algolia queries
  _schemaV2.graphql
  package.json
  src/config.ts
  src/schema/v2/system/algolia/index.ts
  src/schema/v2/system/index.ts
  yarn.lock
Labels: Jira Synced

#3348 feat: expose partner field under FairExhibitor type
  _schemaV2.graphql
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/fair.ts
Labels: Jira Synced

#3351 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/__tests__/partner_categories.test.ts
  src/schema/v2/articlesConnection.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/fair.ts
  src/schema/v2/fair_organizer.ts
  src/schema/v2/partner.ts
  src/schema/v2/partner_category.ts
Labels: Jira Synced

#3358 feature: Add displayUSD to auction results realized price
  _schemaV2.graphql
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#3377 feat: add fair sort/filter args to fairOrganizer>fairsConnection
  _schemaV2.graphql
  src/schema/v2/__tests__/fair_organizer.test.ts
  src/schema/v2/fair_organizer.ts
Labels: Jira Synced
