Repository artsy/metaphysics, pull requests merged in 2021-03, with the labels that each got.

#3028 Deploy
  _schema.graphql
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/stitching/causality/__tests__/stitching.test.ts
  src/lib/stitching/causality/schema.ts
  src/lib/stitching/causality/v2/stitching.ts
  src/lib/stitching/logLinkMiddleware.ts
  src/schema/v2/__tests__/partner.test.js
  src/schema/v2/lot.ts
  src/schema/v2/me/__tests__/watchedLotConnection.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/watchedLotConnection.ts
  src/schema/v2/partner.ts
Labels: Jira Synced

#3039 update exchange schema
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Merge On Green

#3043 chore: update bmw arts design sponsored content link
  src/lib/sponsoredContent/data.json
Labels: Jira Synced

#3052 toolchain: Add `yarn test:debug` for debugger
  package.json
Labels: Merge On Green

#3045 Migrate MyBids logic to MP
  _schemaV2.graphql
  src/index.ts
  src/lib/loaders/__tests__/request_id.test.js
  src/lib/loaders/__tests__/user_agent.test.js
  src/lib/loaders/index.ts
  src/lib/loaders/loaders_with_authentication/causality.ts
  src/lib/loaders/loaders_with_authentication/index.ts
  src/lib/stitching/causality/v2/stitching.ts
  src/schema/v1/artwork/artworkContextGrids/index.ts
  src/schema/v2/artwork/artworkContextGrids/index.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/lot.ts
  src/schema/v2/me/__tests__/myBids.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/myBids.ts
  src/schema/v2/me/sale_registrations.ts
  src/schema/v2/me/watchedLotConnection.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/sale_artwork.ts
  src/types/graphql.d.ts
Labels: Merge On Green

#3057 chore: update v2 schema
  _schemaV2.graphql
Labels: Squash On Green

#3060 Remove moment warnings about deprecated method
  src/lib/helpers.ts
Labels: Merge On Green

#3065 refactor: Rename SaleArtwork.lot to lotState
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myBids.test.ts
  src/schema/v2/me/myBids.ts
  src/schema/v2/sale_artwork.ts
Labels: Merge On Green
