Repository artsy/metaphysics, pull requests merged in 2021-09, with the labels that each got.

#3383 fix: Need Bash for Post Deploy
  Dockerfile
Labels: Merge On Green

#3384 fix: Missing Post-Deploy Script
  .dockerignore
  Dockerfile
Labels: Merge On Green

#3386 fix(external): uses id fields
  _schemaV2.graphql
  src/schema/v2/External/External.ts
  src/schema/v2/External/ExternalAuctionHouse.ts
  src/schema/v2/External/ExternalFair.ts
  src/schema/v2/External/ExternalGallery.ts
Labels: Squash On Green

#3391 fix(mutations): use correct name for collector profile input attr
  _schemaV2.graphql
  src/schema/v2/me/update_collector_profile.ts
Labels: Squash On Green

#3402 chore: add shipping contact input in the seller accept offer and counteroffer mutations
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Squash On Green

#3404 fix(PURCHASE-2928): Add disambiguate symbol to swiss frank
  src/lib/currency_codes.json
Labels: Jira Synced

#3409 feat(inquiry): adds contact gallery field
  _schemaV2.graphql
  src/schema/v2/me/conversation/submit_inquiry_request_mutation.ts
Labels: Squash On Green

#3410 fix: [HomePageArtworkModules] Respect exclude argument
  src/schema/v2/home/home_page_artwork_modules.ts
Labels: Merge On Green

#3407 FX-3277 Send fair organizer id to gravity instead of it's pofile id
  src/schema/v2/fair_organizer.ts
Labels: Jira Synced

#3408 fix(FX-3294): Group fair exhibitors by numeric or special character within `#` group
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/fair.ts
Labels: Jira Synced

#3417 fix: postinstall-prepare
  package.json
Labels: Merge On Green

#3418 fix: Chalk
  package.json
  yarn.lock
Labels: Merge On Green

#3414 feat(FX-3301): return sorted letters in order for `exhibitorsGroupedByName`
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/fair.ts
Labels: Jira Synced

#3421 chore: @artsy/morgan
  package.json
  src/index.ts
  yarn.lock
Labels: Squash On Green

#3412 fix(FX-3300): return only running fairs
  src/schema/v2/home/__tests__/home_page_artwork_modules.test.js
  src/schema/v2/home/fetch.ts
Labels: Jira Synced

#3422 feat: [OrderedSet] Add additional Profile type
  src/schema/v2/item.ts
  src/types/runtime/gravity/OrderedSet.ts
Labels: Squash On Green

#3425 feat: [Profile] Add `location` field
  src/schema/v2/profile.ts
Labels: Merge On Green

#3427 feat(schema): exposes page
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/page.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#3420 feat: Affinity score
  _schemaV2.graphql
  src/lib/apis/vortex.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/lib/loaders/loaders_without_authentication/vortex.ts
  src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/newWorksByInterestingArtists.ts
Labels: Jira Synced, Squash On Green

#3434 fix: authenticate vortex graphql loader
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_with_authentication/vortex.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/lib/loaders/loaders_without_authentication/vortex.ts
Labels: Jira Synced

#3435 fix: Filter out sold artworks for newWorksByInterestingArtists
  src/schema/v2/me/__tests__/newWorksByInterestingArtists.test.ts
  src/schema/v2/me/newWorksByInterestingArtists.ts
Labels: Jira Synced

#3438 docs: Copy schema design doc over from playbook
  docs/graphql-schema-design.md
Labels: Merge On Green

#3442 feat: Add showsByFollowedArtists
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/showsByFollowedArtists.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/showsByFollowedArtists.ts
Labels: Jira Synced

#3451 fix(showsconnection): uses connection from array slice
  src/schema/v2/__tests__/shows.test.js
  src/schema/v2/shows.ts
Labels: Merge On Green
