Repository artsy/metaphysics, pull requests merged in 2021-11, with the labels that each got.

#3512 feat[SWA-39]: Enable multiple assets to be added to a submission
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Jira Synced

#3517 Feat(CX-2018): My Collection Visual Profile [Metaphysics]
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
  src/schema/v2/me/__tests__/deleteCollectorProfileIconMutation.test.js
  src/schema/v2/me/__tests__/update_me_mutation.test.js
  src/schema/v2/me/deleteCollectorProfileIconMutation.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#3518 feat: Add flag to exclude purchased artworks from My Collection query
  _schema.graphql
  _schemaV2.graphql
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced, Squash On Green

#3526 fix(partnersConnection): removes null/undefined values from gravity args
  src/schema/v2/partners.ts
Labels: Merge On Green

#3531 feat(schema): exposes partner category
  _schemaV2.graphql
  src/schema/v2/schema.ts
Labels: Merge On Green

#3533 feat:stitch devices under User
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green

#3534 fix: propagate a requests xapp token when using stitching
  src/index.ts
  src/lib/stitching/gravity/link.ts
  src/types/graphql.d.ts
Labels: Merge On Green

#3537 feat(me): exposes additional fields for settings
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/index.ts
Labels: Merge On Green

#3544 fix(saved-artworks): adds page & size args
  _schemaV2.graphql
  src/schema/v2/me/savedArtworks.ts
Labels: Merge On Green

#3551 Update convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Merge On Green

#3554 Update convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Merge On Green

#3557 Deploy
  _schemaV2.graphql
  docs/pagination.md
  src/lib/helpers.ts
  src/schema/v2/fields/pagination.ts
  src/schema/v2/me/followed_genes.ts
  src/schema/v2/me/savedArtworks.ts
Labels: Jira Synced

#3564 fix: make format arg not required
  _schemaV2.graphql
  src/schema/v2/fair.ts
  src/schema/v2/show.ts
  src/schema/v2/show_event.ts
Labels: Squash On Green

#3555 feat(CX-2131): Add artist recommendations
  _schemaV2.graphql
  src/lib/helpers.ts
  src/schema/v2/me/__tests__/artistRecommendations.test.ts
  src/schema/v2/me/artistRecommendations.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/newWorksByInterestingArtists.ts
Labels: Jira Synced

#3566 Deploy
  _schemaV2.graphql
  src/lib/helpers.ts
  src/schema/v2/me/__tests__/artistRecommendations.test.ts
  src/schema/v2/me/artistRecommendations.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/newWorksByInterestingArtists.ts
Labels: Jira Synced
