Repository artsy/metaphysics, pull requests merged in 2021-04, with the labels that each got.

#3074 chore: run yarn dump:local to get schema up-to-date
  _schemaV2.graphql
Labels: Merge On Green

#3081 under revert of Diffusion/Vortex stitching change
  _schema.graphql
  _schemaV2.graphql
  src/data/diffusion.graphql
  src/data/vortex.graphql
  src/lib/stitching/diffusion/link.ts
  src/lib/stitching/diffusion/schema.ts
  src/lib/stitching/diffusion/v1/stitching.ts
  src/lib/stitching/diffusion/v2/stitching.ts
  src/lib/stitching/mergeSchemas.ts
  src/lib/stitching/vortex/schema.ts
Labels: Merge On Green

#3072 fix: Sidestep batch loader to fix SaleRegistrationConnection
  src/schema/v2/me/__tests__/sale_registrations.test.js
  src/schema/v2/me/sale_registrations.ts
Labels: Jira Synced

#3085 fix: Merge watched and bidded-on artworks
  src/schema/v2/me/myBids.ts
Labels: Merge On Green

#3098 feat: increase max pod count to 28.
  hokusai/production.yml
Labels: Merge On Green

#3095 Deploy
  .circleci/config.yml
  .gitignore
  _schemaV2.graphql
  hokusai/production.yml
  jest.config.js
  jest.config.v1.js
  jest.config.v2.js
  package.json
  src/schema/v2/gene.ts
  src/schema/v2/location.ts
Labels: Jira Synced

#3108 feature: Support unfollows in followGene mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/follow_gene.test.js
  src/schema/v2/me/__tests__/follow_gene.test.ts
  src/schema/v2/me/follow_gene.ts
Labels: Jira Synced

#3109 fix: make follow gene test more specific
  src/schema/v2/me/__tests__/follow_gene.test.ts
Labels: Jira Synced, Merge On Green

#3113 Deploy
  _schemaV2.graphql
  src/lib/__tests__/helpers.test.ts
  src/lib/helpers.ts
  src/schema/v2/__tests__/show.test.js
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/filterArtworksConnection.ts
  src/schema/v2/partner.ts
  src/schema/v2/show.ts
  src/schema/v2/sorts/show_sorts.ts
Labels: Jira Synced
