Repository artsy/metaphysics, pull requests merged in 2021-12, with the labels that each got.

#3572 Revert "[COORDINATE-DEPLOY] feat: relax VAT requirements for artworks (TX-135)"
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#3577 feat: adds update password mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/updateMyPasswordMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#3575 Deploy
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/data/convection.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/schema/v2/__tests__/phoneNumber.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/phoneNumber.ts
  src/schema/v2/schema.ts
  yarn.lock
Labels: Jira Synced

#3580 feat(FX-3624): Add "sizes" attribute to SearchCriteria and SearchCriteriaAttributes
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Labels: Jira Synced

#3214 feat: hybrid conversation message+event connection
  _schemaV2.graphql
  src/lib/base64.ts
  src/lib/loaders/loaders_with_authentication/causality.ts
  src/lib/loaders/loaders_with_authentication/exchange.ts
  src/lib/loaders/loaders_with_authentication/index.ts
  src/schema/v2/fields/hybridConnection/README.md
  src/schema/v2/fields/hybridConnection/fetchHybridConnection.test.ts
  src/schema/v2/fields/hybridConnection/fetchHybridConnection.ts
  src/schema/v2/fields/hybridConnection/hybridConnectionFromArraySlice.ts
  src/schema/v2/fields/hybridConnection/hybridOffsets.test.ts
  src/schema/v2/fields/hybridConnection/hybridOffsets.ts
  src/schema/v2/fields/hybridConnection/index.ts
  src/schema/v2/me/__tests__/myBids.test.ts
  src/schema/v2/me/conversation/eventConnection/index.ts
  src/schema/v2/me/conversation/eventConnection/messageEvents.ts
  src/schema/v2/me/conversation/eventConnection/orderEvents.ts
  src/schema/v2/me/conversation/index.ts
  src/schema/v2/me/conversation/message.ts
  src/schema/v2/me/myBids.ts
Labels: Squash On Green

#3609 chore: use Squash on Green label when pushing schema updates to client repos
  scripts/push-schema-changes.js
Labels: Squash On Green

#3617 Deploy
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/data/convection.graphql
  src/data/gravity.graphql
  src/lib/stats.js
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/schema/v2/me/__tests__/bidder_position.test.js
  src/schema/v2/me/bidder_position_messages.ts
  yarn.lock
Labels: Jira Synced

#3634 feat[SWA-166] Create RemoveAssetFromConsignmentSubmission mutation
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Jira Synced

#3637 Deploy
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Jira Synced
