Repository artsy/metaphysics, pull requests merged in 2021-02, with the labels that each got.

#2952 feat: Adds offerable_from_inquiry flag for Inquiry Checkout
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/edition_set.ts
  src/schema/v2/sellable.ts
  src/types/gravity/artworkResponse.d.ts
  src/types/runtime/gravity/Artwork.ts
  src/types/runtime/gravity/EditionSet.ts
Labels: Jira Synced

#2969 feat: support artwork classification aggregation
  _schemaV2.graphql
  src/schema/v2/aggregations/filter_artworks_aggregation.ts
Labels: Jira Synced, Merge On Green

#2964 chore(classifications): remove deprecated options & descriptions
  src/config.ts
  src/lib/attributionClasses.ts
  src/schema/v2/artworkAttributionClasses.ts
  src/types/gravity/artworkResponse.d.ts
Labels: Squash On Green

#2974 When creating an inquiry-offer-order, associate the offer and order in the mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/impulse.ts
  src/lib/stitching/exchange/__tests__/stitching.test.ts
  src/lib/stitching/exchange/__tests__/testingUtils.ts
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced, Squash On Green

#2979 chore: expose colors + partner(s) for filtering API
  _schemaV2.graphql
  src/schema/v2/aggregations/filter_artworks_aggregation.ts
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#2983 feature: Artwork price paid mutations for artworks
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Merge On Green

#2984 chore(CI): Set ignore-engines globally when pushing schema changes
  scripts/push-schema-changes.js
Labels: Squash On Green

#2994 Add conversation to Order type (with new root conversation field)
  _schemaV2.graphql
  src/lib/stitching/exchange/__tests__/stitching.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
  src/schema/v2/schema.ts
Labels: Jira Synced, Squash On Green

#3001 fix: dont use query params for PUT/POST requests
  src/lib/apis/fetch.ts
  src/lib/loaders/__tests__/request_id.test.js
  src/lib/loaders/__tests__/user_agent.test.js
  src/lib/loaders/api/index.ts
  src/lib/loaders/api/loader_interface.ts
  src/lib/loaders/api/loader_with_authentication_factory.ts
  src/lib/loaders/api/loader_without_authentication_factory.ts
  src/lib/loaders/api/loader_without_cache_factory.ts
Labels: Merge On Green

#3003 Revert "fix: dont use query params for PUT/POST requests"
  src/lib/apis/fetch.ts
  src/lib/loaders/__tests__/request_id.test.js
  src/lib/loaders/__tests__/user_agent.test.js
  src/lib/loaders/api/index.ts
  src/lib/loaders/api/loader_interface.ts
  src/lib/loaders/api/loader_with_authentication_factory.ts
  src/lib/loaders/api/loader_without_authentication_factory.ts
  src/lib/loaders/api/loader_without_cache_factory.ts
Labels: Squash On Green

#3002 Don't show "not open yet" fairs in home module
  package.json
  src/schema/v2/home/__tests__/__snapshots__/home_page_fairs_module.test.js.snap
  src/schema/v2/home/__tests__/home_page_fairs_module.test.js
  src/schema/v2/home/home_page_fairs_module.ts
  src/test/helper.js
  yarn.lock
Labels: Jira Synced

#3010 feat: add locationCities to filter args
  _schemaV2.graphql
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#3012 feat: Add orderConnection to Conversation
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
  src/lib/stitching/exchange/__tests__/stitching.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced
