Repository artsy/metaphysics, pull requests merged in 2021-05, with the labels that each got.

#3126 fix: Add page type in args
  src/schema/v2/partner.ts
Labels: Merge On Green

#3122 Deploy
  _schemaV2.graphql
  hokusai/staging.yml
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/partner.test.js
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/partner.ts
Labels: Jira Synced

#3128 Updates schema
  _schemaV2.graphql
Labels: Merge On Green

#3125 chore: stitch updated gravity schema (PX-3983)
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/schema.ts
Labels: Jira Synced

#3138 Update exchange schema with inquiry checkout phase 2 flags/mutations
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Merge On Green

#3132 Deploy
  .circleci/config.yml
  _schema.graphql
  _schemaV2.graphql
  package.json
  src/data/exchange.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/schema.ts
  yarn.lock
Labels: Jira Synced

#3139 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/partner.test.js
  src/schema/v2/partner.ts
Labels: Jira Synced

#3141 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/partner.test.js
  src/schema/v2/partner.ts
  yarn.lock
Labels: Jira Synced

#3148 feature: Set 2x Images to Use 50 Quality
  src/schema/v2/image/__tests__/cropped.test.ts
  src/schema/v2/image/__tests__/resized.test.ts
  src/schema/v2/image/cropped.ts
  src/schema/v2/image/resized.ts
Labels: Squash On Green

#3145 fix(resized): correctly handles situations where we pass both a width and a height
  src/schema/v2/image/__tests__/resized.test.ts
  src/schema/v2/image/resized.ts
Labels: Merge On Green

#3156 Deploy
  _schemaV2.graphql
  src/schema/v2/partners.ts
Labels: Jira Synced

#3184 fix: Pin TS version 4.2.4
  package.json
  yarn.lock
Labels: Merge On Green

#3175 feat: Adjust currency in price display text to match brand guide
  src/lib/__tests__/moneyHelpers.test.ts
  src/lib/currency_codes.json
  src/lib/moneyHelpers.ts
  src/schema/v2/__tests__/auction_result.test.ts
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/auction_result.ts
Labels: Jira Synced
