Repository artsy/metaphysics, pull requests merged in 2022-05, with the labels that each got.

#4016 feat: Introduce myCollectionAuctionResults
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/myCollectionAuctionResults.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/myCollectionAuctionResults.ts
Labels: Jira Synced

#4026 fix: Use internal IDs for MyCollectionAuctionResults artist matching
  src/schema/v2/me/__tests__/myCollectionAuctionResults.test.ts
  src/schema/v2/me/myCollectionAuctionResults.ts
Labels: Jira Synced

#4033 feat(NX-3163): createInquiryOrder mutation
  _schemaV2.graphql
  src/lib/stitching/exchange/__tests__/stitching.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced

#4047 chore(FX-3878): small improvements for graphql upload and reverseImageSearch query
  _schemaV2.graphql
  src/config.ts
  src/schema/v2/reverseImageSearch.ts
Labels: Squash On Green

#4046 feat(FX-3940): query for an artwork within a tineye match
  _schemaV2.graphql
  src/schema/v2/__tests__/reverseImageSearch.test.ts
  src/schema/v2/reverseImageSearch.ts
Labels: Jira Synced

#4002 feat [CX-2453]: Expose location object to create and update My Collection artwork mutations
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
  src/schema/v2/me/myLocation.ts
  src/schema/v2/me/update_me_mutation.ts
Labels: Jira Synced

#4054 Deploy
  .env.test
  _schema.graphql
  _schemaV2.graphql
  peril/upstreamSchemaValidator.ts
  src/config.ts
  src/data/exchange.graphql
  src/data/kaws.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/lib/stitching/kaws/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/kaws/__tests__/schema.test.ts
  src/lib/stitching/kaws/__tests__/stitching.test.ts
  src/lib/stitching/kaws/__tests__/testingUtils.ts
  src/lib/stitching/kaws/link.ts
  src/lib/stitching/kaws/schema.ts
  src/lib/stitching/kaws/v1/stitching.ts
  src/lib/stitching/kaws/v2/stitching.ts
  src/lib/stitching/mergeSchemas.ts
  src/schema/v2/__tests__/filterArtworksConnection.test.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/fair.ts
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
  src/schema/v2/me/myLocation.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/system/services/metaphysics.ts
Labels: Jira Synced

#4068 fix(NX-3138): add conversation to CommerceBuyOrder in stitching
  _schemaV2.graphql
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced

#4071 Dump latest schema
  _schemaV2.graphql
Labels: Merge On Green

#4065 feat: add additional payment methods
  _schemaV2.graphql
  src/lib/stitching/exchange/__tests__/additionalPaymentMethods.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced

#4081 fix: correct shape for lot standings to properly return sold status after sale is closed
  src/schema/v2/me/__tests__/myBids.test.ts
  src/schema/v2/me/myBids.ts
Labels: Jira Synced

#4074 Expose artworks_count and artists_count in myCollectionInfo
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/__tests__/myCollectionInfo.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/myCollection.ts
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4083 fix: Adjust My Collection info resolver
  src/schema/v2/me/__tests__/myCollectionInfo.test.ts
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4101 fix(article): filters out unsupported section types
  src/schema/v2/article/index.ts
Labels: Merge On Green
