Repository artsy/metaphysics, pull requests merged in 2022-12, with the labels that each got.

#4565 feat: use cost Major for price paid in MyC
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Jira Synced

#4563 feat(FX-4473): notificationsConnection has new field objects_count
  _schemaV2.graphql
  src/schema/v2/notifications/__tests__/index.test.ts
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#4566 Deploy
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
  src/schema/v2/notifications/__tests__/index.test.ts
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#4536 feat(conversations): Add remaining Conversations v2 Mutations
  _schemaV2.graphql
  src/lib/gravityErrorHandler.ts
  src/lib/loaders/api/loader_with_authentication_factory.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/loaders/loaders_with_authentication/impulse.ts
  src/schema/v2/artwork/__tests__/updateArtworkMutation.test.ts
  src/schema/v2/artwork/updateArtworkMutation.ts
  src/schema/v2/conversation/__tests__/__snapshots__/update_conversation_mutation.test.js.snap
  src/schema/v2/conversation/__tests__/deleteConversationMutation.test.ts
  src/schema/v2/conversation/__tests__/updateMessageMutation.test.ts
  src/schema/v2/conversation/__tests__/update_conversation_mutation.test.js
  src/schema/v2/conversation/deleteConversationMutation.ts
  src/schema/v2/conversation/index.ts
  src/schema/v2/conversation/updateMessageMutation.ts
  src/schema/v2/conversation/update_conversation_mutation.ts
  src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
  src/schema/v2/partner/__tests__/updatePartnerFlagsMutation.test.ts
  src/schema/v2/partner/partner.ts
  src/schema/v2/partner/partnerInquirerCollectorProfile.ts
  src/schema/v2/partner/updatePartnerFlagsMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green, Jira Synced

#4585 feat: add user coordinates for user location
  _schemaV2.graphql
  src/schema/v2/me/update_me_mutation.ts
Labels: Jira Synced

#4591 chore: alphabetically order gravity auth loaders
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Merge On Green

#4580 feat: allow filtering for upcoming lots
  _schemaV2.graphql
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/me/auction_results_by_followed_artists.ts
  src/schema/v2/me/myCollectionAuctionResults.ts
Labels: Jira Synced, Squash On Green

#4604 fix(updateMessageMutation): Fix type caps case
  _schemaV2.graphql
  src/schema/v2/conversation/__tests__/updateMessageMutation.test.ts
  src/schema/v2/conversation/updateMessageMutation.ts
Labels: Merge On Green

#4608 feat (art quiz): add quiz endpoint
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/fields/pagination.ts
  src/schema/v2/quiz.ts
  src/schema/v2/quizArtworkConnection.ts
  src/schema/v2/schema.ts
  src/schema/v2/updateQuizMutation.ts
  src/schema/v2/user.ts
Labels: Jira Synced

#4621 feat(me): adds quiz field
  _schemaV2.graphql
  src/schema/v2/me/index.ts
Labels: Merge On Green

#4619 refactor: improve auctionResultsConnection interface [DO NOT MERGE]
  _schemaV2.graphql
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/auction_result.ts
  src/schema/v2/me/auction_results_by_followed_artists.ts
  src/schema/v2/me/myCollectionAuctionResults.ts
Labels: Squash On Green

#4629 feat: NX-3400 Initials on User
  _schemaV2.graphql
  src/schema/v2/user.ts
Labels: Jira Synced

#4628 feat(type): expose types from InquirerCollectorProfile on CollectorProfileType
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/partner/partnerInquirerCollectorProfile.ts
Labels: Jira Synced

#4635 fix(null): create a fallback when name is null
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#4638 chore(deps): bumps img
  package.json
  yarn.lock
Labels: Merge On Green

#4620 feat(CX-3253): Enable Unauthenticated users ability to create consignment inquiries
  _schemaV2.graphql
  src/config.ts
  src/lib/apis/convection.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_without_authentication/convection.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/schema/v2/consignments/createConsignmentInquiryMutation.ts
  src/schema/v2/consignments/utils/formatCreateConsignmentError.ts
Labels: Jira Synced

#4640 Deploy
  _schemaV2.graphql
  src/config.ts
  src/lib/apis/convection.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_without_authentication/convection.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/consignments/createConsignmentInquiryMutation.ts
  src/schema/v2/consignments/utils/formatCreateConsignmentError.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
Labels: Jira Synced

#4631 feat: only non-expired credit cards are qualified
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
Labels: Squash On Green

#4644 feat: add ordered sets connection
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/OrderedSet/OrderedSet.ts
  src/schema/v2/OrderedSet/__tests__/orderedSetsConnection.test.ts
  src/schema/v2/OrderedSet/orderedSets.ts
  src/schema/v2/OrderedSet/orderedSetsConnection.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#4656 feat: Add includePersonalArtists param to collectedArtistsConnection
  _schemaV2.graphql
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4657 fix: Set includePersonalArtists to true for artwork form query
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced, Squash On Green

#4659 fix: adjust includePersonalArtists hack
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4662 feat: support ordered set internal name field
  _schemaV2.graphql
  src/schema/v2/OrderedSet/OrderedSet.ts
  src/schema/v2/OrderedSet/createOrderedSetMutation.ts
Labels: Jira Synced
