Repository artsy/metaphysics, pull requests merged in 2022-04, with the labels that each got.

#3922 feat: update stitched `savedSearchesConnection` to support new `sort` input argument
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Jira Synced

#3882 feat [CX-2427]: Adding artist insights into my collection artworks
  src/lib/loadBatchPriceInsights.ts
  src/lib/loaders/loaders_with_authentication/vortex.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced, Squash On Green

#3942 Fix: Update schema
  _schemaV2.graphql
Labels: Squash On Green

#3939 feat: Update Gravity GraphQL schema
  _schema.graphql
  _schemaV2.graphql
  src/data/gravity.graphql
  src/lib/stitching/gravity/__tests__/__snapshots__/schema.test.ts.snap
Labels: Jira Synced

#3947 feat(FX-3851): Implement HomePageMarketingCollectionsModule & add grav-backed collections under Artist, Fair, and Viewer
  _schemaV2.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/lib/stitching/kaws/__tests__/stitching.test.ts
  src/lib/stitching/kaws/v2/stitching.ts
  src/schema/v2/fair.ts
Labels: Jira Synced

#3973 fix(channel): adds articles connection removes pinned articles
  _schemaV2.graphql
  src/schema/v2/article/channel.ts
Labels: Merge On Green

#3978 Revert "[PX-4946] Remove fallbacks + deprecated arta related fields"
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced, Squash On Green

#3965 feature(artwork page) Add data and models to back embedded video on the artwork page
  _schemaV2.graphql
  src/schema/v2/artwork/artworkVideos.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/types/Video.ts
Labels: Jira Synced

#3990 feat: exposes greenhouse jobs data
  _schemaV2.graphql
  src/lib/apis/greenhouse.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_without_authentication/greenhouse.ts
  src/lib/loaders/loaders_without_authentication/index.ts
  src/schema/v2/jobs.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#3995 [GRO-861] add include_fallback_artists param to related artists schema
  _schemaV2.graphql
  src/schema/v2/artist/related.ts
Labels: Merge On Green, Jira Synced

#3996 feat: use latest version of artsy managed orbs, and track app version in k8s. (PLATFORM-4103)
  .circleci/config.yml
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#3930 feat: update user schema and mutations for order notifications
  _schemaV2.graphql
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/__tests__/update_me_mutation.test.js
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/user.ts
Labels: hackathon

#3991 feat(FX-3873): dev can pass an image as an argument to `doNotUseImageSearch` query
  _schemaV2.graphql
  package.json
  src/config.ts
  src/index.ts
  src/schema/v2/imageSearch.ts
  src/schema/v2/schema.ts
  yarn.lock
Labels: Jira Synced
