Repository artsy/metaphysics, pull requests merged in 2022-01, with the labels that each got.

#3639 Deploy
  _schemaV2.graphql
  package.json
  src/config.ts
  src/extensions/errorExtension.ts
  src/extensions/loggingExtension.ts
  src/index.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/me/__tests__/update_me_mutation.test.js
  src/schema/v2/me/collector_profile.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/partner.ts
  src/test/gql-server.js
  tsconfig.json
  yarn.lock
Labels: Jira Synced

#3641 Revert "feat(PX-4058): partner transition part 3"
  src/schema/v2/partner.ts
Labels: Jira Synced

#3642 Deploy
  src/schema/v2/partner.ts
Labels: Jira Synced

#3643 Revert "Revert "feat(PX-4058): partner transition part 3""
  src/schema/v2/partner.ts
Labels: Jira Synced

#3647 feat(stitching): Update positron schema
  src/data/positron.graphql
Labels: Merge On Green

#3648 feat(stitching): Update positron schema
  src/data/positron.graphql
Labels: Merge On Green

#3644 Deploy
  _schema.graphql
  _schemaV2.graphql
  src/data/positron.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/stitching/mergeSchemas.ts
  src/lib/stitching/positron/link.ts
  src/lib/stitching/positron/schema.ts
  src/schema/v2/index.ts
  src/schema/v2/me/delete_account_mutation.ts
  src/schema/v2/partner.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#3649 chore: generate stitched schema
  _schema.graphql
  _schemaV2.graphql
Labels: Squash On Green

#3652 feat(articles): adds featured argument
  _schemaV2.graphql
  src/schema/v2/articlesConnection.ts
Labels: Merge On Green

#3653 docs(workshop): Add workshop link
  README.md
Labels: Merge On Green

#3654 Deploy
  README.md
  _schema.graphql
  _schemaV2.graphql
  src/lib/stitching/mergeSchemas.ts
  src/lib/stitching/positron/link.ts
  src/lib/stitching/positron/schema.ts
  src/schema/v2/article/__tests__/article.test.js
  src/schema/v2/article/index.ts
  src/schema/v2/article/sections/ArticleSectionCallout.ts
  src/schema/v2/article/sections/ArticleSectionEmbed.ts
  src/schema/v2/article/sections/ArticleSectionImageCollection.ts
  src/schema/v2/article/sections/ArticleSectionImageSet.ts
  src/schema/v2/article/sections/ArticleSectionSocialEmbed.ts
  src/schema/v2/article/sections/ArticleSectionText.ts
  src/schema/v2/article/sections/ArticleSectionVideo.ts
  src/schema/v2/articlesConnection.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#3658 feat(artist dupes): expose new sorts and fields for artists
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/sorts/artist_sorts.ts
Labels: hackathon

#3659 chore: expose me.partners
  _schemaV2.graphql
  src/schema/v2/me/index.ts
  src/schema/v2/me/partners.ts
Labels: hackathon

#3668 fix: Set excludePurchasedArtworks to false
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced

#3657 feat(articles): fleshes out article schema
  _schemaV2.graphql
  src/schema/v2/article/index.ts
  src/schema/v2/article/models.ts
  src/schema/v2/article/sections/ArticleSectionImageCollection.ts
  src/schema/v2/article/sections/ArticleSectionImageSet.ts
  src/schema/v2/article/sections/ArticleSectionText.ts
  src/schema/v2/image/index.ts
Labels: Merge On Green

#3672 feat: Add otherRelevantPosition to collector profile
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
Labels: Jira Synced

#3674 fix(article): filters out unpublished artworks
  _schemaV2.graphql
  src/schema/v2/article/sections/ArticleSectionImageCollection.ts
  src/schema/v2/article/sections/ArticleSectionImageSet.ts
Labels: Merge On Green

#3685 fix(mutations): corrects extended types
  _schemaV2.graphql
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green
