Repository artsy/metaphysics, pull requests merged in 2022-08, with the labels that each got.

#4272 Update Exchange schema
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Jira Synced

#4286 feat(FX-4136): expose the enablement flag from Gravity for Fair/Show
  src/config.ts
  src/schema/v2/__tests__/fair.test.js
  src/schema/v2/__tests__/show.test.js
  src/schema/v2/fair.ts
  src/schema/v2/show.ts
Labels: Jira Synced

#4290 feat: Add medianSalePriceDisplayText to artwork price insights
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/vortex.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
Labels: Jira Synced

#4312 feat: add marketPriceInsights to the artwork interface
  _schemaV2.graphql
  package.json
  src/lib/__tests__/formatLargeNumber.test.ts
  src/lib/fillers/enrichArtworksWithPriceInsights.ts
  src/lib/formatLargeNumber.ts
  src/lib/ifFieldRequested.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
  yarn.lock
Labels: Squash On Green

#4304 feat: expose additional user fields for admin clients
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/schema.ts
  src/schema/v2/user.ts
  src/schema/v2/users/addUserRoleMutation.ts
  src/schema/v2/users/createUserAdminNoteMutation.ts
  src/schema/v2/users/deleteUserRoleMutation.ts
  src/schema/v2/users/updateUserMutation.ts
  src/schema/v2/users/updateUserSaleProfileMutation.ts
Labels: Jira Synced

#4309 feat(PX-5114): Artwork page: Update buyer-facing shipping copy
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#4315 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/schema.ts
  src/schema/v2/user.ts
  src/schema/v2/users/addUserRoleMutation.ts
  src/schema/v2/users/createUserAdminNoteMutation.ts
  src/schema/v2/users/deleteUserRoleMutation.ts
  src/schema/v2/users/updateUserMutation.ts
  src/schema/v2/users/updateUserSaleProfileMutation.ts
Labels: Jira Synced

#4323 chore: Update vortex schema
  _schemaV2.graphql
  src/data/vortex.graphql
Labels: Squash On Green

#4336 feat: extend user_sale_profile type
  _schemaV2.graphql
  src/schema/v2/user.ts
  src/schema/v2/userSaleProfile.ts
Labels: Jira Synced

#4340 fix: casing and types
  _schemaV2.graphql
  src/schema/v2/userSaleProfile.ts
Labels: Merge On Green

#4354 fix: Return image square placeholder when no geometry is provided
  src/schema/v2/image/__tests__/index.test.js
  src/schema/v2/image/index.ts
Labels: Jira Synced
