Repository artsy/metaphysics, pull requests merged in 2022-10, with the labels that each got.

#4424 feat: add deleteUserAdminNote mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/deleteUserAdminNoteMutation.test.ts
  src/schema/v2/schema.ts
  src/schema/v2/users/deleteUserAdminNoteMutation.ts
Labels: Jira Synced

#4438 fix: use errorOrResponse pattern for user role mutations
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/users/addUserRoleMutation.ts
  src/schema/v2/users/deleteUserRoleMutation.ts
Labels: Jira Synced

#4446 feat: web deployment to prefer spot tier
  hokusai/production.yml
  hokusai/staging.yml
Labels: Jira Synced

#4448 fix: move this expensive line out of request loop
  src/index.ts
Labels: Merge On Green

#4443 feat: Add support for remote images to My Collection artwork mutations
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/update_me_mutation.ts
Labels: Jira Synced

#4453 chore: add comment about the artwork price insights type
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Squash On Green

#4452 feat(FX-4313): Add the ability to query a formatted date for notification
  _schemaV2.graphql
  src/schema/v2/notifications/__tests__/index.test.ts
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#4459 feat(CX-3000): Expose has price estimate boolean field
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#4467 fix: add a fallback name to User if one is not set
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/user.ts
Labels: Squash On Green

#4462 fix: Adjust logic to get the default artwork images to not return broken images without URL
  src/schema/v2/image/__tests__/index.test.js
  src/schema/v2/image/index.ts
Labels: Jira Synced

#4477 feat(FX-4212): add receivePartnerShowNotification user preference
  _schemaV2.graphql
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/__tests__/update_me_mutation.test.js
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/user.ts
Labels: Jira Synced
