Repository artsy/metaphysics, pull requests merged in 2022-03, with the labels that each got.

#3817 fix: Adjust comparableAuctionResultsLoader path
  src/lib/loaders/loaders_without_authentication/diffusion.ts
  src/schema/v2/artwork/comparableAuctionResults.ts
Labels: Squash On Green

#3824 feat(alerts): add support for new colors
  src/lib/colors.ts
  src/schema/v2/__tests__/searchCriteriaLabel.test.ts
  src/schema/v2/searchCriteriaLabel.ts
Labels: Squash On Green

#3825 fix(article): fixes when articles are missing channel ids
  src/schema/v2/article/index.ts
Labels: Merge On Green

#3835 feat: add endedAt to SaleArtwork type
  _schemaV2.graphql
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/sale_artwork.ts
Labels: Bidding Engine

#3846 fix(article): omit tags for in vertical query
  src/schema/v2/article/index.ts
Labels: Merge On Green

#3840 feat: Increase number of considered artists for AuctionResultsByFollowedArtists to 200
  src/schema/v2/me/auction_results_by_followed_artists.ts
Labels: Jira Synced

#3837 feat: Add isP1 field to artist target supply
  _schemaV2.graphql
  src/schema/v2/artist/targetSupply/__tests__/index.test.ts
  src/schema/v2/artist/targetSupply/index.ts
Labels: Jira Synced

#3842 feat: Add formattedStartDateTime to MP
  _schemaV2.graphql
  src/lib/date.ts
  src/schema/v2/__tests__/sale_artwork.test.js
  src/schema/v2/sale/__tests__/index.test.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/sale_artwork.ts
Labels: Squash On Green

#3849 fix(article): fallback to author field before editors default
  src/schema/v2/article/__tests__/article.test.ts
  src/schema/v2/article/index.ts
Labels: Merge On Green

#3850 feat(article): exposes lead paragraph
  _schemaV2.graphql
  src/schema/v2/article/index.ts
Labels: Merge On Green

#3852 feat: update convection schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
  src/lib/stitching/convection/schema.ts
Labels: Squash On Green

#3854 fix(article): early null on media
  src/schema/v2/article/index.ts
Labels: Merge On Green

#3869 feat: Update Convection GraphQL schema
  _schema.graphql
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Jira Synced

#3876 bug:ensure auctions detail formatted start date time works with live auction integrations
  _schemaV2.graphql
  src/lib/date.ts
  src/schema/v2/sale/__tests__/index.test.ts
  src/schema/v2/sale/index.ts
Labels: Squash On Green, Bidding Engine

#3886 feat: Add importSource to artworks
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Labels: Jira Synced, Squash On Green

#3885 feat: Add submissionId to myCollectionUpdateArtworkMutation input fields
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Jira Synced

#3894 fix(me): awaits loader so as to catch errors
  src/schema/v2/me/update_me_mutation.ts
Labels: Merge On Green

#3903 chore(GRO-844): Remove input values that aren't used by Gravity
  _schemaV2.graphql
  src/schema/v2/notification_preferences.ts
Labels: Jira Synced

#3904 Deploy
  _schemaV2.graphql
  src/schema/v2/notification_preferences.ts
Labels: Jira Synced

#3912 fix: Check if ComparableAuctionResults date is a valid integer
  src/lib/__tests__/helpers.test.ts
  src/lib/helpers.ts
  src/schema/v2/artwork/comparableAuctionResults.ts
Labels: Jira Synced

#3918 Add very basic mutation for updating users
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/schema.ts
  src/schema/v2/users/updateUserMutation.ts
Labels: Merge On Green, hackathon

#3926 feat: Allow more user updates
  _schemaV2.graphql
  src/schema/v2/users/updateUserMutation.ts
Labels: Merge On Green, hackathon

#3927 feat: Add data transfer bool for user
  _schemaV2.graphql
  src/schema/v2/user.ts
  src/schema/v2/users/updateUserMutation.ts
Labels: hackathon
