Repository artsy/metaphysics, pull requests merged in 2022-11, with the labels that each got.

#4486 feat(video): add video dimensions to type
  src/schema/v2/artwork/__tests__/utilities.test.ts
  src/schema/v2/artwork/utilities.ts
Labels: Merge On Green

#4491 feat(video): adds id
  _schemaV2.graphql
  src/schema/v2/types/Video.ts
Labels: Merge On Green

#4494 chore: return `null` in TaxInfo when artwork is NOT eligible for on-platform transaction
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/artwork/isInAuctionResolver.ts
  src/schema/v2/artwork/taxInfo.ts
  src/schema/v2/artwork/utilities.ts
Labels: Squash On Green

#4503 chore(video): Remove `url` field on video
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/utilities.test.ts
  src/schema/v2/artwork/utilities.ts
  src/schema/v2/types/Video.ts
Labels: Merge On Green

#4505 fix(artist): fixes related shows pagination
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/shows.ts
  src/schema/v2/fields/pagination.ts
Labels: Merge On Green

#4500 feat(CX-3053): define logic to show the embedded carousel within metaphysics
  _schemaV2.graphql
  src/schema/v2/home/__tests__/home_page_my_collection_onboarding_module.test.ts
  src/schema/v2/home/home_page_my_collection_onboarding_module.ts
  src/schema/v2/home/index.ts
Labels: Squash On Green

#4510 fix(artist): correctly passes size argument
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
Labels: Merge On Green

#4519 fix(fair): adds page/size support to articles connection
  _schemaV2.graphql
  src/schema/v2/fair.ts
Labels: Merge On Green

#4515 feat: admin note includes creator name when available
  _schemaV2.graphql
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/user.ts
Labels: Squash On Green

#4490 feat(art-quiz) Add DislikedArtwork mutation and REST loaders
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/dislike_artwork.test.js
  src/schema/v2/me/dislikeArtworkMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#4521 feat(FX-4437): Add curated marketing collections query field
  _schemaV2.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Jira Synced

#4531 Deploy
  _schemaV2.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/conversation/conversations.ts
  src/schema/v2/me/__tests__/conversations.test.js
  src/schema/v2/schema.ts
Labels: Jira Synced

#4535 feat(sendConversationMessage): Expand mutation to include full API
  _schemaV2.graphql
  src/index.ts
  src/lib/loaders/api/extensionsLogger.ts
  src/schema/v2/conversation/__tests__/__snapshots__/send_message_mutation.test.js.snap
  src/schema/v2/conversation/__tests__/send_message_mutation.test.js
  src/schema/v2/conversation/send_message_mutation.ts
Labels: Merge On Green, Jira Synced

#4551 feat(NX-3340): add volt-v2 to schema updates
  scripts/push-schema-changes.js
Labels: Jira Synced

#4553 feat(volt-v2): add to schema push
  scripts/push-schema-changes.js
Labels: Merge On Green

#4432 chore: sort query params when generating a Gemini CDN URL
  src/config.ts
  src/schema/v2/artist/__tests__/carousel.test.js
  src/schema/v2/image/__tests__/cropped.test.ts
  src/schema/v2/image/__tests__/resized.test.ts
  src/schema/v2/image/services/gemini.ts
Labels: Merge On Green
