Repository artsy/metaphysics, pull requests merged in 2022-06, with the labels that each got.

#4112 feat(NX-3129): add shortArrayDescription to attributionClass of artwork
  _schemaV2.graphql
  src/lib/attributionClasses.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/attributionClass.ts
Labels: Jira Synced

#4119 chore: update Exchange schema
  _schema.graphql
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Jira Synced

#4121 Deploy
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/insights.test.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/insights.ts
Labels: Jira Synced

#4127 feat [CX-2605]: Add the list of the artists in My Collection to myCollectionInfo
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionInfo.test.ts
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4135 Deploy
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollectionInfo.test.ts
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#4157 feat(artist-insights): make metaphysics single source of truth for querying artist insights
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/insights.test.ts
  src/schema/v2/artist/insights.ts
Labels: Merge On Green

#4151 feat: Add sorting by most recent insight update to My Collection artwork connection
  _schemaV2.graphql
  src/lib/loadBatchPriceInsights.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced

#4173 fix: Return uniq artworks when passing sortByLastAuctionResultDate to My Collection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
Labels: Squash On Green

#4186 chore: remove additional payment methods field
  _schemaV2.graphql
  src/lib/stitching/exchange/__tests__/additionalPaymentMethods.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Jira Synced
