Repository artsy/metaphysics, pull requests merged in 2023-06, with the labels that each got.

#5060 Revert "Only return all active hero units"
  src/schema/v2/HeroUnit/heroUnitsConnection.ts
Labels: Merge On Green

#5077 feat: add profilesConnection
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/profiles.test.ts
  src/schema/v2/profiles.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#5100 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/verify_address.test.ts
  src/schema/v2/schema.ts
  src/schema/v2/verifyAddress.ts
Labels: Jira Synced

#5098 feat: support sending and fetching source id on IDV
  _schemaV2.graphql
  src/schema/v2/__tests__/identityVerification.test.ts
  src/schema/v2/identityVerification.ts
  src/schema/v2/me/__tests__/sendIdentityVerficationEmailMutation.test.ts
  src/schema/v2/me/sendIdentityVerficationEmailMutation.ts
Labels: Squash On Green

#5105 chore: update schema and stitching after upstream Algolia removal
  src/data/gravity.graphql
  src/lib/stitching/gravity/schema.ts
Labels: Jira Synced

#5107 feat: remove user id from comparables query
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#5110 chore: update exchange schema
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Merge On Green
