Repository artsy/metaphysics, pull requests merged in 2023-07, with the labels that each got.

#5103 feat: Add private param to me createUserInterestMutation
  _schemaV2.graphql
  src/schema/v2/me/__tests__/createUserInterestMutation.test.ts
  src/schema/v2/me/createUserInterestMutation.ts
  src/schema/v2/userInterests.ts
Labels: Jira Synced, Squash On Green

#5126 feat(artist): alters high auction record insights label & description
  src/schema/v2/artist/__tests__/helpers.test.ts
  src/schema/v2/artist/helpers.ts
Labels: Merge On Green, Jira Synced

#5131 fix: incorrect & inconsistent address validation fields
  _schemaV2.graphql
  src/schema/v2/__tests__/verify_address.test.ts
  src/schema/v2/verifyAddress.ts
Labels: Jira Synced

#5136 feat(artist): adds series meta tags
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/helpers.test.ts
  src/schema/v2/artist/helpers.ts
  src/schema/v2/artist/meta.ts
Labels: Merge On Green

#5123 feat(ONYX-116): support sorting collections by recency
  _schemaV2.graphql
  src/schema/v2/me/__tests__/collectionsConnection.test.ts
  src/schema/v2/me/collectionsConnection.ts
Labels: Jira Synced

#5150 feat: me userInterest field
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/userInterest.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/userInterest.ts
  src/schema/v2/userInterests.ts
Labels: Jira Synced, Squash On Green

#5155 feat: do not use spot in staging
  hokusai/staging.yml
Labels: Jira Synced

#5092 feat(CX-3724): Mutations - UserInterests and Artists You Collect
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/createUserInterestsMutation.test.ts
  src/schema/v2/me/__tests__/deleteUserInterestsMutation.test.ts
  src/schema/v2/me/__tests__/userInterestsConnection.test.ts
  src/schema/v2/me/createUserInterestMutation.ts
  src/schema/v2/me/createUserInterestsMutation.ts
  src/schema/v2/me/deleteUserInterestsMutation.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/userInterestsConnection.ts
  src/schema/v2/schema.ts
  src/schema/v2/userInterests.ts
Labels: Jira Synced, Squash On Green

#5157 feat: Add artistIDs param to myCollectionConnection
  _schemaV2.graphql
  src/lib/__tests__/helpers.test.ts
  src/lib/helpers.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Labels: Jira Synced

#5163 feat(ONYX-159): support interest id filtering within userInterestsConnection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/userInterestsConnection.test.ts
  src/schema/v2/me/userInterestsConnection.ts
Labels: Jira Synced

#5165 feat(ONYX-160): add updateUserInterest mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/updateUserInterestMutation.test.ts
  src/schema/v2/me/updateUserInterestMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#5167 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/updateUserInterestMutation.test.ts
  src/schema/v2/me/updateUserInterestMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#5172 chore: add comment to delete user interest mutation
  _schemaV2.graphql
  src/schema/v2/me/deleteUserInterestMutation.ts
Labels: Squash On Green

#5164 feat: add verified representatives to Artist schema
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/artist/__tests__/verifiedRepresentatives.test.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/verifiedRepresentatives.ts
Labels: Jira Synced

#5168 feat(AMBER-28): create messages and conversation events query
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/impulse.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/conversationEvent.ts
  src/schema/v2/conversation/index.ts
  src/schema/v2/partner/partner.ts
Labels: Squash On Green

#5115 feat: add GAINING_FOLLOWERS artist insight
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/helpers.test.ts
  src/schema/v2/artist/helpers.ts
Labels: Jira Synced

#5182 chore: Deprecate collectedArtistsConnection
  _schemaV2.graphql
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced
