Repository artsy/metaphysics, pull requests merged in 2023-10, with the labels that each got.

#5331 feat: remove the old created year aggregation for auction results
  src/lib/loaders/loaders_without_authentication/diffusion.ts
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#5346 chore: Updates gravity graphql schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Merge On Green

#5363 Revert "feat: update prediction mp schema"
  scripts/push-schema-changes.js
Labels: Merge On Green

#5371 fix: Expose sort argument in gravity stitching for searchCriteriaConnection
  _schemaV2.graphql
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green

#5367 chore: update gravity gql schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Merge On Green

#5379 chore: add some non-nullability to user roles
  _schemaV2.graphql
  src/schema/v2/system/userRoles.ts
Labels: Merge On Green

#5385 feat(searchCriteriaConnection): Add `represented` argument to field
  .eslintrc.json
  _schemaV2.graphql
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Squash On Green
