Repository artsy/metaphysics, pull requests merged in 2023-11, with the labels that each got.

#5384 fix: adding missing color to saved search preview name
  src/lib/colors.ts
Labels: Jira Synced

#5380 feat: Add metric support to Saved Search display name and labels
  src/schema/v2/__tests__/previewSavedSearch.test.ts
  src/schema/v2/__tests__/searchCriteriaLabel.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/searchCriteriaLabel.ts
Labels: Jira Synced, Squash On Green

#5406 chore: simplify S3 path for shared configuration
  package.json
  scripts/setup.sh
Labels: Merge On Green

#5407 fix(ONYX-523): update labels for ways to buy
  src/schema/v2/__tests__/previewSavedSearch.test.ts
  src/schema/v2/__tests__/searchCriteriaLabel.test.ts
  src/schema/v2/searchCriteriaLabel.ts
Labels: Jira Synced

#5416 feat: introduce mock structure for suggested filters
  _schemaV2.graphql
  src/schema/v2/__tests__/previewSavedSearch.test.ts
  src/schema/v2/previewSavedSearch.ts
Labels: Jira Synced

#5418 feat(ONYX-520): add rarity as a suggested filter
  src/schema/v2/__tests__/previewSavedSearch.test.ts
  src/schema/v2/previewSavedSearch.ts
Labels: Jira Synced

#5422 feat: move some metadata onto the edge between Alert and Artist nodes
  _schemaV2.graphql
  src/schema/v2/alerts.ts
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
Labels: Merge On Green

#5421 Deploy
  .env.development
  _schemaV2.graphql
  hokusai/development.yml
  src/schema/v2/__tests__/previewSavedSearch.test.ts
  src/schema/v2/alerts.ts
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/previewSavedSearch.ts
Labels: Jira Synced

#5436 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/createPartnerOfferMutation.ts
  src/schema/v2/partnerOffer.ts
  src/schema/v2/sorts/artwork_sorts.ts
Labels: Jira Synced

#5441 feat(EMI-1557): add receivePartnerOfferNotification
  _schemaV2.graphql
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/me/__tests__/__snapshots__/update_me_mutation.test.js.snap
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/__tests__/update_me_mutation.test.js
  src/schema/v2/me/index.ts
  src/schema/v2/me/update_me_mutation.ts
  src/schema/v2/user.ts
Labels: Jira Synced
