Repository artsy/metaphysics, pull requests merged in 2023-01, with the labels that each got.

#4666 chore: Minor artist insights copy changes GRO-1440
  src/schema/v2/artist/helpers.ts
Labels: Merge On Green

#4670 feat(TX-947): add medium and attribution class to artwork version type
  _schemaV2.graphql
  src/schema/v2/artwork_version.ts
Labels: Jira Synced

#4672 feat(CX-2964): add isProfileComplete to Collector Profile
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
Labels: Jira Synced

#4647 feat(art-quiz) create triggerCampaignMutation and gravity loader
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/triggerCampaignMutation.test.ts
  src/schema/v2/me/triggerCampaignMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#4685 chore: bump json5
  yarn.lock
Labels: Merge On Green

#4642 feat(FX-4497): Article featured artist activity
  _schemaV2.graphql
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#4689 feat(TX-948): add attribution class fields to artwork version
  _schemaV2.graphql
  src/schema/v2/artwork_version.ts
Labels: Jira Synced

#4692 fix(requestlocation): better handles error cases
  src/schema/v2/requestLocation.ts
Labels: Merge On Green

#4679 feat(FX-4534): GraphQL mutation for marking a specific entry in the activity panel as read
  _schemaV2.graphql
  src/schema/v2/me/__tests__/mark_notification_as_read_mutation.test.ts
  src/schema/v2/me/mark_notification_as_read_mutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#4691 feat: Expose images in update artwork mutation
  src/schema/v2/me/__tests__/myCollectionCreateArtworkMutation.test.ts
  src/schema/v2/me/__tests__/myCollectionUpdateArtworkMutation.test.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Jira Synced

#4698 feat(NX-3371): Expose message's to and cc
  _schemaV2.graphql
  src/schema/v2/conversation/__tests__/__snapshots__/message.test.js.snap
  src/schema/v2/conversation/__tests__/message.test.js
  src/schema/v2/conversation/message.ts
Labels: Jira Synced

#4701 chore(NX-3371): make message's to and cc non-nullable
  _schemaV2.graphql
  src/schema/v2/conversation/message.ts
Labels: Jira Synced

#4700 feat: add CRUD and listings for FeaturedLink
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/FeaturedLink/__tests__/createFeaturedLinkMutation.test.ts
  src/schema/v2/FeaturedLink/__tests__/deleteFeaturedLinkMutation.test.ts
  src/schema/v2/FeaturedLink/__tests__/featuredLinksConnection.test.ts
  src/schema/v2/FeaturedLink/__tests__/updateFeaturedLinkMutation.test.ts
  src/schema/v2/FeaturedLink/createFeaturedLinkMutation.ts
  src/schema/v2/FeaturedLink/deleteFeaturedLinkMutation.ts
  src/schema/v2/FeaturedLink/featuredLink.ts
  src/schema/v2/FeaturedLink/featuredLinksConnection.ts
  src/schema/v2/FeaturedLink/updateFeaturedLinkMutation.ts
  src/schema/v2/item.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#4702 feat(CX-2847): GraphQLLong
  _schemaV2.graphql
  src/lib/customTypes/GraphQLLong.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Labels: Jira Synced

#4707 Revert "feat(CX-2847): GraphQLLong"
  _schemaV2.graphql
  src/lib/customTypes/GraphQLLong.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
Labels: Jira Synced

#4704 feat(wishlists): add artworksConnection to me.collection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/collection.test.ts
  src/schema/v2/me/collection.ts
  src/schema/v2/sorts/collection_sorts.ts
Labels: Squash On Green

#4709 Feat(CX-2847): Updated GraphQLLong
  _schemaV2.graphql
  src/lib/customTypes/GraphQLLong.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/me/myCollectionCreateArtworkMutation.ts
  src/schema/v2/me/myCollectionUpdateArtworkMutation.ts
Labels: Jira Synced

#4718 feat(FX-4523): me.collectionsConnection
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/collectionsConnection.test.ts
  src/schema/v2/me/collection.ts
  src/schema/v2/me/collectionsConnection.ts
  src/schema/v2/me/index.ts
Labels: Jira Synced

#4721 fix(NX-3412): gracefully handle errors from fromUser
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#4722 feat(NX-3406): add date formatter to arstyUserSince field
  src/schema/v2/CollectorProfile/collectorProfile.ts
Labels: Jira Synced

#4724 feat(FX-4524): add createCollection mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/createCollectionMutation.test.ts
  src/schema/v2/me/createCollectionMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#4723 feat(NX-3411): Enable `to_be_replied` param to filter new conversations
  _schemaV2.graphql
  src/schema/v2/conversation/conversations.ts
Labels: Jira Synced

#4727 feat(wishlists): add deleteCollection mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/deleteCollectionMutation.test.ts
  src/schema/v2/me/deleteCollectionMutation.ts
  src/schema/v2/schema.ts
Labels: Squash On Green

#4737 fix: surfaces error messages
  src/schema/v2/me/unlinkAuthenticationMutation.ts
Labels: Merge On Green, Jira Synced
