Repository artsy/metaphysics, pull requests merged in 2023-08, with the labels that each got.

#5189 feat: add curated_trending and curated_emerging to artist insights
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/helpers.test.ts
  src/schema/v2/artist/helpers.ts
Labels: Jira Synced

#5178 feat: add fields and arguments for price range filter
  _schemaV2.graphql
  src/lib/__tests__/moneyHelper.test.ts
  src/lib/loaders/loaders_without_authentication/diffusion.ts
  src/lib/moneyHelper.ts
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/aggregations/filterAuctionResultsAggregation.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#5194 feat: use uncached filterArtworksLoader when filtering by price within a sale
  src/schema/v2/__tests__/filterArtworksConnection.test.ts
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#5195 fix: check for *-* priceRange filters, as thats not really filtering
  src/schema/v2/__tests__/filterArtworksConnection.test.ts
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#5205 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/__tests__/verify_address.test.ts
  src/schema/v2/aggregations/filterAuctionResultsAggregation.ts
  src/schema/v2/artist/helpers.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/updateArtistMutation.ts
  src/schema/v2/verifyAddress.ts
Labels: Jira Synced

#5207 Add missing mutation input
  _schemaV2.graphql
  src/schema/v2/artist/updateArtistMutation.ts
Labels: Merge On Green

#5215 Remove execute bit from random file
  src/schema/v2/partner/partner.ts
Labels: Merge On Green

#5221 feat(ONYX-259): Allow admins to query a user's My Collection artworks
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/user.ts
Labels: Jira Synced

#5225 chore: use an authenticated loader for search to be able to use unleash on the backend
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Merge On Green

#5244 feat(searchCriteriaConnection): Stitch in connection to root `Query`
  _schemaV2.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Squash On Green

#5245 feat(searchCriteria): Stitch in connection to root `Viewer`
  _schemaV2.graphql
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green

#5249 chore(stitching): Update gravity schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Merge On Green
