Repository artsy/metaphysics, pull requests merged in 2023-05, with the labels that each got.

#4988 feat: Add show recommendations field under me
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/showsConnection.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/showsConnection.ts
Labels: Jira Synced

#4989 Feat(CX-3663): Sort and ExcludeClosedLots params
  _schemaV2.graphql
  src/schema/v2/sale_artworks.ts
Labels: Jira Synced

#4993 Deploy
  _schemaV2.graphql
  src/schema/v2/sale_artworks.ts
Labels: Jira Synced

#4992 feat: Add location support to me showsConnection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/showsConnection.test.ts
  src/schema/v2/me/showsConnection.ts
Labels: Jira Synced, Squash On Green

#5001 fix(trending artists): handle invalid/empty response more defensively
  src/schema/v2/artists/__tests__/curatedTrending.test.ts
  src/schema/v2/artists/curatedTrending.ts
Labels: Squash On Green

#5000 chore: make my collection info node
  _schemaV2.graphql
  src/schema/v2/me/myCollectionInfo.ts
Labels: Squash On Green

#5003 Revert "chore: make my collection info node"
  _schemaV2.graphql
  src/schema/v2/me/myCollectionInfo.ts
Labels: Squash On Green

#4997 feat: Add collected_artworks_count to collection artists endpoint
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
  src/schema/v2/me/__tests__/myCollectionInfo.test.ts
Labels: Squash On Green

#5005 chore: Remove all param from collectedArtists resolver
  src/schema/v2/me/myCollectionInfo.ts
Labels: Jira Synced

#5012 feat: optionally return the set when adding or removing a set item
  _schemaV2.graphql
  src/schema/v2/OrderedSet/__tests__/addOrderedSetItemMutation.test.ts
  src/schema/v2/OrderedSet/__tests__/deleteOrderedSetItemMutation.test.ts
  src/schema/v2/OrderedSet/addOrderedSetItemMutation.ts
  src/schema/v2/OrderedSet/deleteOrderedSetItemMutation.ts
Labels: Jira Synced

#5023 feat(NX-3538): add filter by from_id in ConversationsConnection
  _schemaV2.graphql
  src/schema/v2/conversation/conversations.ts
Labels: Jira Synced

#5022 feat: add ability to pass `includesArtworkID` arg to `collectionsConnection`
  _schemaV2.graphql
  src/schema/v2/me/__tests__/collectionsConnection.test.ts
  src/schema/v2/me/collectionsConnection.ts
Labels: Jira Synced

#5032 feat(NX-3537): add artistId filter to conversationConnection query
  _schemaV2.graphql
  src/schema/v2/conversation/conversations.ts
Labels: Jira Synced

#5035 chore(NX-3537): Fix name of param passed as artist id to conversations
  src/schema/v2/conversation/conversations.ts
Labels: Jira Synced

#5040 feat: support marketable arg for saleArtworks connection
  _schemaV2.graphql
  src/schema/v2/sale_artworks.ts
Labels: Jira Synced

#5024 chore(GRO-1671): update meta tags based on the selected tab on the Artist page
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/meta.test.js
  src/schema/v2/artist/meta.ts
Labels: Jira Synced

#5043 Deploy
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/meta.test.js
  src/schema/v2/artist/meta.ts
Labels: Jira Synced

#5047 feat: Add follow and sort args to partnersConnection
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/locationHelpers.ts
  src/schema/v2/me/showsConnection.ts
  src/schema/v2/partner/partners.ts
Labels: Jira Synced, Squash On Green

#5044 feat(NX-3536): Add query for collector profiles search.
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfiles.ts
  src/schema/v2/__tests__/collectorProfiles.test.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#5046 feat: add user id to comparables query
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#5048 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/locationHelpers.ts
  src/schema/v2/CollectorProfile/collectorProfiles.ts
  src/schema/v2/__tests__/collectorProfiles.test.ts
  src/schema/v2/auction_result.ts
  src/schema/v2/conversation/conversations.ts
  src/schema/v2/me/showsConnection.ts
  src/schema/v2/partner/partners.ts
  src/schema/v2/schema.ts
Labels: Jira Synced
