Repository artsy/metaphysics, pull requests merged in 2023-04, with the labels that each got.

#4926 Feat(CX-3574): Support Lots ASC param
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#4927 Deploy
  src/schema/v2/auction_result.ts
Labels: Jira Synced

#4932 Revert "fix(CX-3459): Update collector profile resolvers"
  src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/me/__tests__/update_collector_profile.test.js
  src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
Labels: Jira Synced

#4933 feat(cx-3543): Update curated collection list
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Jira Synced

#4936 feat(FX-4725): allow counting only visible artworks for collections
  _schemaV2.graphql
  src/schema/v2/me/__tests__/collection.test.ts
  src/schema/v2/me/collection.ts
Labels: Jira Synced

#4935 Deploy
  _schemaV2.graphql
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/index.ts
  src/schema/v2/me/__tests__/collection.test.ts
  src/schema/v2/me/collection.ts
Labels: Jira Synced

#4941 feat: update pagination for auction results.
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
  src/schema/v2/fields/__tests__/pagination.test.js
  src/schema/v2/fields/pagination.ts
Labels: Jira Synced

#4945 fix: Reduce number of loaded artists in AuctionResultsByFollowedArtists
  src/lib/loaders/helpers.ts
Labels: Jira Synced

#4956 feat(NX-3505): conversation dismissed is false by default on query
  src/schema/v2/conversation/conversations.ts
Labels: Jira Synced

#4952 feat(NX-3437): add unread fields for Partner and Collector
  _schemaV2.graphql
  src/schema/v2/conversation/__tests__/__snapshots__/conversation.test.js.snap
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#4953 [Release on 4/18] Update the help center URL for Zendesk to Salesforce transition # Summary
  src/schema/v2/artwork/taxInfo.ts
Labels: DO NOT MERGE, help links migration

#4967 chore(NX-3438): Allow updateConversation mutation to update toLastViewedMessageId
  _schemaV2.graphql
  src/schema/v2/conversation/__tests__/update_conversation_mutation.test.js
  src/schema/v2/conversation/update_conversation_mutation.ts
Labels: Jira Synced, Squash On Green

#4969 feat: Allow trusted clients to fetch sale artworks by user ID
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/__tests__/sale_artworks.test.ts
  src/schema/v2/sale_artworks.ts
Labels: Jira Synced

#4968 Deploy
  .vscode/launch.json
  _schemaV2.graphql
  src/lib/__tests__/helpers.test.ts
  src/lib/helpers.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/__tests__/sale_artworks.test.ts
  src/schema/v2/conversation/__tests__/update_conversation_mutation.test.js
  src/schema/v2/conversation/update_conversation_mutation.ts
  src/schema/v2/sale_artworks.ts
Labels: Jira Synced

#4971 Feat(CX-2613): Use MeMyCollectionArtworksEndpoint for MyCollection Artworks
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced

#4976 fix: bump request body limit to 1mb from 100kb
  index.js
  src/index.ts
  src/lib/bodyParserMiddleware.ts
Labels: Merge On Green

#4937 feat(pref center): update metaphysics to support channel field for push
  _schemaV2.graphql
  src/schema/v2/__tests__/notification_preferences.test.ts
  src/schema/v2/notification_preferences.ts
Labels: Jira Synced
