Repository artsy/metaphysics, pull requests merged in 2023-09, with the labels that each got.

#5257 feat: Add city name to requestLocation
  _schemaV2.graphql
  src/schema/v2/__tests__/requestLocation.test.ts
  src/schema/v2/requestLocation.ts
Labels: Jira Synced

#5268 chore(stitching): Sync gravity schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Squash On Green

#5269 feat(artist): adds public and blurb fields as inputs
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/updateArtistMutation.ts
Labels: Merge On Green

#5267 Deploy
  _schemaV2.graphql
  src/data/gravity.graphql
  src/schema/v2/__tests__/auction_results.test.js
  src/schema/v2/__tests__/verify_address.test.ts
  src/schema/v2/aggregations/filterAuctionResultsAggregation.ts
  src/schema/v2/artist/groupIndicator.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/targetSupply/index.ts
  src/schema/v2/artist/updateArtistMutation.ts
  src/schema/v2/verifyAddress.ts
Labels: Jira Synced

#5270 chore: Update with latest gravity schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Squash On Green

#5276 feat: add isSavedToList to Artwork type
  _schemaV2.graphql
  src/lib/stitching/gravity/schema.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#5280 chore: update gravity schema
  _schemaV2.graphql
  src/data/gravity.graphql
Labels: Merge On Green

#5304 chore: remove outdated link to Jenkins (PHIRE-276)
  README.md
Labels: Merge On Green

#5315 fix(artist): returns null for bio when partner bio is false and we do not have a blurb
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
Labels: Jira Synced
