Repository artsy/metaphysics, pull requests merged in 2023-03, with the labels that each got.

#4838 feat: newWorksFromGalleriesYouFollow artworks connection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/newWorksFromGalleriesYouFollow.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/newWorksFromGalleriesYouFollow.ts
Labels: Jira Synced

#4836 fix: Artwork Recommendations Connection
  src/schema/v2/me/artworkRecommendations.ts
Labels: Jira Synced

#4842 feat(FX-4599): add collectionsConnection to artwork field
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/collectionsConnection.ts
Labels: Jira Synced

#4843 feat: SimilarToRecentlyViewed connection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/similarToRecentlyViewed.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/similarToRecentlyViewed.ts
Labels: Jira Synced

#4845 Deploy
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/similarToRecentlyViewed.test.ts
  src/schema/v2/me/collectionsConnection.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/similarToRecentlyViewed.ts
Labels: Jira Synced

#4847 fix: Adjust SimilarToRecentlyViewed artwork connection
  src/schema/v2/me/similarToRecentlyViewed.ts
Labels: Jira Synced

#4849 fix: Change ShowsByFollowedArtists default sorting to created_at desc
  src/schema/v2/me/showsByFollowedArtists.ts
Labels: Jira Synced, Squash On Green

#4855 Feat(CX-3410): Introduce optional recipient_email to ConsignmentInquiryMutation
  _schemaV2.graphql
  src/schema/v2/consignments/createConsignmentInquiryMutation.ts
Labels: Jira Synced

#4858 Deploy
  _schemaV2.graphql
  src/schema/v2/consignments/createConsignmentInquiryMutation.ts
Labels: Jira Synced

#4866 Deploy
  _schemaV2.graphql
  src/schema/v2/home/results.ts
  src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts
  src/schema/v2/me/recentlyViewedArtworks.ts
  src/schema/v2/me/sendIdentityVerficationEmailMutation.ts
Labels: Jira Synced

#4868 fix(CX-3459): Update collector profile resolvers
  src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/me/__tests__/update_collector_profile.test.js
  src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
Labels: Jira Synced

#4871 fix: reverts profile loaders change
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Merge On Green

#4869 Deploy
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/CollectorProfile/__tests__/updateCollectorProfileWithID.test.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/home/results.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/me/__tests__/recentlyViewedArtworks.test.ts
  src/schema/v2/me/__tests__/update_collector_profile.test.js
  src/schema/v2/me/recentlyViewedArtworks.ts
  src/schema/v2/partner/__tests__/partnerInquirerCollectorProfile.test.ts
Labels: Jira Synced

#4875 chore(NX-3485): Enable delivery pending flag to be passed as an arg to messages
  _schemaV2.graphql
  src/schema/v2/conversation/__tests__/message.test.js
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#4880 feat(artwork): exposes dominant colors
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#4885 chore (app home screen): update curated collections
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Jira Synced

#4888 feat(CX-3524): Add isPriceEstimateRequestable field to artwork type
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#4894 Deploy
  src/schema/v2/__tests__/auction_result.test.ts
  src/schema/v2/auction_result.ts
Labels: Merge On Green

#4889 chore (app search screen): update curated collections
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Jira Synced

#4899 feat(FX-4681): extract `userID` from `context` for collections
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/collection.ts
  src/schema/v2/me/collectionsConnection.ts
Labels: Jira Synced

#4900 Deploy
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/collection.ts
  src/schema/v2/me/collectionsConnection.ts
Labels: Merge On Green

#4897 feat: delete a user
  _schemaV2.graphql
  src/lib/gravityErrorHandler.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/deleteUserMutation.test.ts
  src/schema/v2/me/delete_account_mutation.ts
  src/schema/v2/schema.ts
  src/schema/v2/users/deleteUserMutation.ts
Labels: Squash On Green

#4906 feat(mutation): adds me field to create saved search payload
  _schemaV2.graphql
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green

#4910 feat: add pagesConnection plus CRUD mutations for Page
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/Feature/UpdateFeatureMutation.ts
  src/schema/v2/Match.ts
  src/schema/v2/Page/CreatePageMutation.ts
  src/schema/v2/Page/DeletePageMutation.ts
  src/schema/v2/Page/Page.ts
  src/schema/v2/Page/PagesConnection.ts
  src/schema/v2/Page/UpdatePageMutation.ts
  src/schema/v2/Page/__tests__/CreatePageMutation.test.ts
  src/schema/v2/Page/__tests__/DeletePageMutation.test.ts
  src/schema/v2/Page/__tests__/PagesConnection.test.ts
  src/schema/v2/Page/__tests__/UpdatePageMutation.test.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#4912 chore: support Date ASC sorting MP
  _schemaV2.graphql
  src/schema/v2/auction_result.ts
Labels: Squash On Green

#4915 chore: adjust is upcoming logic to match diffusion
  src/schema/v2/auction_result.ts
Labels: Squash On Green

#4917 chore: expose isInArtsyAuction
  _schemaV2.graphql
  src/schema/v2/__tests__/auction_result.test.ts
  src/schema/v2/auction_result.ts
Labels: Jira Synced
