Repository artsy/metaphysics, pull requests merged in 2024-12, with the labels that each got.

#6278 refactor: fixes some misalignments between stitched / unstitched viewing rooms
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/stitching/gravity/schema.ts
  src/schema/v2/viewingRoom.ts
  src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomArtworksMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomSubsectionsMutation.test.ts
  src/schema/v2/viewingRooms/mutations/createViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/deleteViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/publishViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/unpublishViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomArtworks.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomSubsections.ts
Labels: DO NOT MERGE

#6255 chore(perf): clean up unused systemTimeLoader
  src/lib/loaders/loaders_without_authentication/gravity.ts
Labels: performance

#6282 feat(DIA-1014): infinite discovery home view section
  package.json
  src/lib/featureFlags.ts
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  yarn.lock
Labels: Art Advisor

#6289 Deploy
  _schemaV2.graphql
  package.json
  src/lib/featureFlags.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
  src/schema/v2/artwork/artworkConsignmentSubmissionType.ts
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  yarn.lock
Labels: Jira Synced

#6293 feat: adding digital art to artworkMediums for artwork grid filtering
  src/lib/artworkMediums.ts
  src/schema/v2/__tests__/artworkMediums.test.ts
Labels: Jira Synced

#6296 chore(perf): rely on shows endpoint instead of related/shows, where possible (DIA-1008)
  src/schema/v2/artwork/artworkContextGrids/__tests__/auctionContext.test.ts
  src/schema/v2/artwork/artworkContextGrids/__tests__/defaultContext.test.ts
  src/schema/v2/artwork/artworkContextGrids/__tests__/fairContext.test.ts
  src/schema/v2/artwork/artworkContextGrids/__tests__/showContext.test.ts
  src/schema/v2/artwork/artworkContextGrids/index.ts
  src/schema/v2/artwork/context.ts
  src/schema/v2/artwork/index.ts
Labels: performance

#6297 feat(home view): allow section declaration to specify a minimum required Eigen version
  package.json
  src/lib/__tests__/semanticVersioning.test.ts
  src/lib/fetchPersistedQuery.ts
  src/lib/semanticVersioning.ts
  src/schema/v2/homeView/helpers/__tests__/isSectionDisplayable.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/index.ts
  yarn.lock
Labels: Squash On Green

#6309 chore(debugging home view): chatty logs for home view sections
  src/lib/semanticVersioning.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
Labels: Squash On Green

#6311 fix(home view): relax auth requirement for infinite discovery card
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
Labels: Merge On Green

#6312 chore: revert disco debugging logs
  src/lib/semanticVersioning.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
Labels: Squash On Green

#6316 fix: use constant limit and fix the clause for initial taste
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6318 fix: improvements for discoverArtworks
  src/lib/infiniteDiscovery/findSimilarArtworks.ts
  src/lib/infiniteDiscovery/getInitialArtworksSample.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green
