Repository artsy/metaphysics, pull requests merged in 2024-03, with the labels that each got.

#5605 feat: allow querying alerts by search criteria
  _schemaV2.graphql
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/previewSavedSearch/previewSavedSearch.ts
Labels: DO NOT MERGE

#5614 feat(followprofile): exposes me under output
  _schemaV2.graphql
  src/schema/v2/me/follow_profile.ts
Labels: Jira Synced

#5624 feat(messages): Add sentAt and messageSentOnPlatform
  _schemaV2.graphql
  src/schema/v2/conversation/message.ts
Labels: Merge On Green

#5586 feat: [EMI-1732] expose user partner offer connections on Me
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/partnerOffer.ts
  src/schema/v2/partnerOfferToCollector.ts
Labels: Jira Synced, DO NOT MERGE

#5626 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
  src/schema/v2/partnerOffer.ts
  src/schema/v2/partnerOfferToCollector.ts
Labels: Jira Synced

#5630 chore: remove collected artist names from collector profile
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
Labels: Jira Synced

#5632 feat(artwork): Add isUnlisted to artwork schema
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#5633 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/updateCollectionsMutation.test.ts
  src/schema/v2/me/updateCollectionsMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced
