Repository artsy/metaphysics, pull requests merged in 2024-11, with the labels that each got.

#6202 feat: hoist up Recently Viewed and Artwork Recs on home
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Jira Synced, Squash On Green

#6172 feat: re-order the homefeed
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Jira Synced, Art Advisor

#6214 fix: user weaviate internal url in resetDiscoveryArtworkReferencesMutation
  src/schema/v2/infiniteDiscovery/resetDiscoveryArtworkReferencesMutation.ts
Labels: Merge On Green

#6219 feat: add ES recommendations for infinite discovery
  _schemaV2.graphql
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6227 feat: differentiates churned gallery page titles
  src/schema/v2/partner/partner.ts
Labels: Jira Synced

#6237 chore(perf): switch to data-saving me/ping endpoint for authentication status
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/__tests__/authenticationStatus.test.ts
  src/schema/v2/authenticationStatus.ts
Labels: performance

#6238 feat: add last mutation, createAndSendBackupSecondFactor
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/stitching/gravity/schema.ts
  src/schema/v2/schema.ts
  src/schema/v2/users/createAndSendBackupSecondFactorMutation.ts
Labels: Merge On Green

#6242 feat: load secrets from vault
  Dockerfile
  hokusai/production.yml
  hokusai/staging.yml
  scripts/load_secrets_and_run.sh
Labels: Jira Synced

#6243 fix: add load secrets script
  Dockerfile
Labels: Merge On Green

#6244 fix: script path
  Dockerfile
Labels: Merge On Green

#6247 feat: resolve time queries immediately instead of from main API
  _schemaV2.graphql
  src/schema/v2/system/__tests__/time.test.js
  src/schema/v2/system/time.ts
Labels: performance

#6263 feat(perf): avoid API requests that are usually unnecessary for Artwork.partner
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: performance

#6276 feat: short-circuit shows call for an artwork if no show_ids
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/artwork/context.ts
Labels: DO NOT MERGE, performance

#6277 Deploy
  src/lib/featureFlags.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/stitching/gravity/schema.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/artwork/context.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/sections/Tasks.ts
  src/schema/v2/homeView/sections/__tests__/Tasks.test.ts
  src/schema/v2/schema.ts
  src/schema/v2/viewingRoomSubsection.ts
  src/schema/v2/viewingRooms/mutations/ARImageInput.ts
  src/schema/v2/viewingRooms/mutations/__tests__/deleteViewingRoomMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/publishViewingRoomMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/unpublishViewingRoomMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomArtworksMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomMutation.test.ts
  src/schema/v2/viewingRooms/mutations/__tests__/updateViewingRoomSubsectionsMutation.test.ts
  src/schema/v2/viewingRooms/mutations/createViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/deleteViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/publishViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/unpublishViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomArtworks.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomMutation.ts
  src/schema/v2/viewingRooms/mutations/updateViewingRoomSubsections.ts
  src/schema/v2/viewingRooms/mutations/viewingRoomInputAttributes.ts
  src/schema/v2/viewingRooms/mutations/viewingRoomOrError.ts
Labels: Jira Synced
