Repository artsy/metaphysics, pull requests merged in 2024-05, with the labels that each got.

#5713 Revert "fix(schema-sync): Update schema sync to also push .json format"
  scripts/push-schema-changes.js
Labels: Squash On Green

#5712 feat(DIA-561): use icon to check collector profile completion and remove bio from it
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
Labels: Jira Synced

#5732 Deploy
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/partnerOffer.ts
  src/schema/v2/partnerOfferToCollector.ts
Labels: Jira Synced

#5733 Update exchange schema
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Jira Synced

#5750 feat: add artist career highlights mutations
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artist/__tests__/careerHighlights.test.ts
  src/schema/v2/artist/careerHighlights.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/careerHighlight/__tests__/createCareerHighlightMutation.test.ts
  src/schema/v2/careerHighlight/__tests__/deleteCareerHighlightMutation.test.ts
  src/schema/v2/careerHighlight/__tests__/updateCareerHighlightMutation.test.ts
  src/schema/v2/careerHighlight/careerHighlight.ts
  src/schema/v2/careerHighlight/createCareerHighlightMutation.ts
  src/schema/v2/careerHighlight/deleteCareerHighlightMutation.ts
  src/schema/v2/careerHighlight/updateCareerHighlightMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#5753 chore: update convection schema
  _schemaV2.graphql
  src/data/convection.graphql
Labels: Squash On Green

#5756 feat(exchange): Extend viewer with commerceOrders exchange field
  _schemaV2.graphql
  src/lib/stitching/exchange/v2/stitching.ts
Labels: Merge On Green

#5759 feat(EMI-1881): Add offerableActivityCount to artwork
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced
