Repository artsy/metaphysics, pull requests merged in 2024-04, with the labels that each got.

#5647 fix(userinterests): returns edge type to support updating ui
  _schemaV2.graphql
  src/schema/v2/me/updateUserInterestMutation.ts
  src/schema/v2/userInterests.ts
Labels: Merge On Green

#5642 feat: add create, update, and read operations for sale agreements
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/SaleAgreements/SaleAgreement.ts
  src/schema/v2/SaleAgreements/SaleAgreementStatusEnum.ts
  src/schema/v2/SaleAgreements/__tests__/createSaleAgreementMutation.test.ts
  src/schema/v2/SaleAgreements/__tests__/saleAgreementsConnection.test.ts
  src/schema/v2/SaleAgreements/__tests__/updateSaleAgreementMutation.test.ts
  src/schema/v2/SaleAgreements/createSaleAgreementMutation.ts
  src/schema/v2/SaleAgreements/saleAgreementsConnection.ts
  src/schema/v2/SaleAgreements/updateSaleAgreementMutation.ts
  src/schema/v2/sale/index.ts
  src/schema/v2/schema.ts
Labels: DO NOT MERGE

#5652 fix(me): adds page/size to args
  _schemaV2.graphql
  src/schema/v2/me/userInterestsConnection.ts
Labels: Merge On Green

#5666 feat: request more MyCollection artwork properties from privileged contexts (ONYX-898)
  src/schema/v2/user.ts
Labels: Jira Synced

#5662 feat: Add previewImages field to Notification type
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/image/normalize.ts
  src/schema/v2/me/__tests__/notification.test.ts
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#5693 feat: Adds partnerProvidedBiography field to Artist
  _schemaV2.graphql
  src/schema/v2/artist/index.ts
Labels: Merge On Green

#5704 chore(ONYX-938): edit the list of specialists, remove specialty field
  _schemaV2.graphql
  src/data/specialistBios.json
  src/schema/v2/__tests__/specialistBios.test.ts
  src/schema/v2/specialistBios.ts
Labels: Squash On Green
