Repository artsy/metaphysics, pull requests merged in 2024-02, with the labels that each got.

#5550 Deploy
  _schemaV2.graphql
  src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
  src/schema/v2/artworkResult/__tests__/index.test.ts
  src/schema/v2/artworkResult/index.ts
  src/schema/v2/createPartnerOfferMutation.ts
Labels: Jira Synced

#5570 feat: Return `me` from notification mutations
  _schemaV2.graphql
  src/schema/v2/me/markNotificationsAsSeenMutation.ts
  src/schema/v2/me/mark_all_notifications_as_read_mutation.ts
  src/schema/v2/me/mark_notification_as_read_mutation.ts
Labels: Jira Synced, Squash On Green

#5582 chore: add searchCriteriaID to Alert type
  _schemaV2.graphql
  src/schema/v2/Alerts/createAlertMutation.ts
  src/schema/v2/Alerts/deleteAlertMutation.ts
  src/schema/v2/Alerts/index.ts
  src/schema/v2/Alerts/updateAlertMutation.ts
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/me/index.ts
Labels: Merge On Green

#5594 feat(DIA-481): wire up CollectorProfile#interestsConnection
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#5595 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#5598 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/unleash.ts
  src/schema/v2/admin/index.ts
  src/schema/v2/admin/mutations/createFeatureFlagMutation.ts
Labels: Merge On Green
