Repository artsy/metaphysics, pull requests merged in 2024-10, with the labels that each got.

#6070 feat: add discover marketing collections to homeview
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/sections/DiscoverMarketingCollections.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Art Advisor

#6085 fix: use unauthenticated artworkLoader for coverArtwork on Artist
  src/schema/v2/artist/index.ts
Labels: Merge On Green

#6079 fix(EMI-2124): no auction signals if no sale artwork, avoid local time comparisons
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced

#6093 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/me/__tests__/dismiss_task_mutation.test.js
  src/schema/v2/me/dismiss_task_mutation.ts
  src/schema/v2/me/task.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6096 chore: use cached data loader for fetching `cities` on `Partner`
  src/schema/v2/partner/partner.ts
Labels: performance

#6087 feat: add HomeViewSectionCards section type
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewCard.ts
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
  src/schema/v2/homeView/sections/ExploreByCategory.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Squash On Green

#6098 chore: use uncached data loader to fetch an artworks artists
  _schemaV2.graphql
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/schema/v2/artwork/index.ts
  src/schema/v2/artworkResult/__tests__/index.test.ts
  src/schema/v2/conversation/__tests__/submit_inquiry_request_mutation.test.ts
  src/schema/v2/test/utils.ts
Labels: performance

#6099 chore: skip lotStandings fetch when the artwork isnt in an auction
  src/schema/v2/artwork/index.ts
Labels: performance

#6100 chore: guard against a null/undefined `body` when resolving partner locations
  src/schema/v2/partner/partner.ts
Labels: Merge On Green

#5893 docs: add docs for creating a new home view section
  docs/adding_a_new_home_view_section.md
Labels: Art Advisor

#6102 refactor: re-organize section types
  docs/adding_a_new_home_view_section.md
  docs/imgs/home-view-sections-and-types.png
  src/schema/v2/homeView/HomeViewCard.ts
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sectionTypes/Activity.ts
  src/schema/v2/homeView/sectionTypes/Articles.ts
  src/schema/v2/homeView/sectionTypes/Artists.ts
  src/schema/v2/homeView/sectionTypes/Artworks.ts
  src/schema/v2/homeView/sectionTypes/AuctionResults.ts
  src/schema/v2/homeView/sectionTypes/Cards.ts
  src/schema/v2/homeView/sectionTypes/DiscoverMarketingCollection.ts
  src/schema/v2/homeView/sectionTypes/ExploreBy.ts
  src/schema/v2/homeView/sectionTypes/Fairs.ts
  src/schema/v2/homeView/sectionTypes/Galleries.ts
  src/schema/v2/homeView/sectionTypes/GenericSectionInterface.ts
  src/schema/v2/homeView/sectionTypes/HeroUnits.ts
  src/schema/v2/homeView/sectionTypes/MarketingCollections.ts
  src/schema/v2/homeView/sectionTypes/Sales.ts
  src/schema/v2/homeView/sectionTypes/Shows.ts
  src/schema/v2/homeView/sectionTypes/ViewingRooms.ts
  src/schema/v2/homeView/sectionTypes/_ExampleSectionType.ts
  src/schema/v2/homeView/sectionTypes/index.ts
  src/schema/v2/homeView/sectionTypes/names.ts
  src/schema/v2/homeView/sections/ActiveBids.ts
  src/schema/v2/homeView/sections/AuctionLotsForYou.ts
  src/schema/v2/homeView/sections/Auctions.ts
  src/schema/v2/homeView/sections/CuratorsPicksEmerging.ts
  src/schema/v2/homeView/sections/DiscoverMarketingCollections.ts
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
  src/schema/v2/homeView/sections/ExploreByCategory.ts
  src/schema/v2/homeView/sections/ExploreByMarketingCollectionCategories.ts
  src/schema/v2/homeView/sections/FeaturedFairs.ts
  src/schema/v2/homeView/sections/GalleriesNearYou.ts
  src/schema/v2/homeView/sections/HeroUnits.ts
  src/schema/v2/homeView/sections/LatestActivity.ts
  src/schema/v2/homeView/sections/LatestArticles.ts
  src/schema/v2/homeView/sections/LatestAuctionResults.ts
  src/schema/v2/homeView/sections/MarketingCollections.ts
  src/schema/v2/homeView/sections/NewWorksForYou.ts
  src/schema/v2/homeView/sections/NewWorksFromGalleriesYouFollow.ts
  src/schema/v2/homeView/sections/News.ts
  src/schema/v2/homeView/sections/RecentlyViewedArtworks.ts
  src/schema/v2/homeView/sections/RecommendedArtists.ts
  src/schema/v2/homeView/sections/RecommendedArtworks.ts
  src/schema/v2/homeView/sections/ShowsForYou.ts
  src/schema/v2/homeView/sections/SimilarToRecentlyViewedArtworks.ts
  src/schema/v2/homeView/sections/TrendingArtists.ts
  src/schema/v2/homeView/sections/ViewingRooms.ts
  src/schema/v2/homeView/sections/_ExampleSection.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/schema.ts
Labels: Squash On Green

#6103 fix: Change `me/tasks` pagination param from `limit` to `size`
  src/schema/v2/me/__tests__/tasks.test.ts
  src/schema/v2/me/index.ts
Labels: Jira Synced

#6094 chore: remove unstitched user devices feature flag
  _schemaV2.graphql
  package.json
  src/config.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/devices.ts
  src/schema/v2/user.ts
Labels: Jira Synced

#6112 fix: include headers: true info in cache key
  src/lib/loaders/api/loader_without_authentication_factory.ts
Labels: Merge On Green

#6095 feat: Add Tasks ("Act Now") section to home view
  _schemaV2.graphql
  src/lib/featureFlags.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/sectionTypes/Tasks.ts
  src/schema/v2/homeView/sectionTypes/index.ts
  src/schema/v2/homeView/sectionTypes/names.ts
  src/schema/v2/homeView/sections/Tasks.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  src/schema/v2/me/dismiss_task_mutation.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/task.ts
Labels: Jira Synced, Art Advisor

#6116 feat(home view): add a HomeViewSectionCard (singular) section type
  _schemaV2.graphql
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/sectionTypes/Card.ts
  src/schema/v2/homeView/sectionTypes/Cards.ts
  src/schema/v2/homeView/sectionTypes/Galleries.ts
  src/schema/v2/homeView/sectionTypes/index.ts
  src/schema/v2/homeView/sectionTypes/names.ts
  src/schema/v2/homeView/sections/GalleriesNearYou.ts
  src/schema/v2/homeView/sections/_ExampleSection.ts
  src/schema/v2/homeView/sections/__tests__/GalleriesNearYou.test.ts
Labels: Squash On Green, Art Advisor

#6114 chore(AMBER-1084): Commerce Opt in and Opt in Report allow for locationID param
  _schemaV2.graphql
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
Labels: Jira Synced

#6117 fix(home view): shape of empty connections
  src/schema/v2/homeView/sectionTypes/Activity.ts
  src/schema/v2/homeView/sectionTypes/Articles.ts
  src/schema/v2/homeView/sectionTypes/AuctionResults.ts
  src/schema/v2/homeView/sectionTypes/Fairs.ts
  src/schema/v2/homeView/sectionTypes/MarketingCollections.ts
  src/schema/v2/homeView/sectionTypes/Sales.ts
  src/schema/v2/homeView/sections/ActiveBids.ts
  src/schema/v2/homeView/sections/Auctions.ts
  src/schema/v2/homeView/sections/FeaturedFairs.ts
  src/schema/v2/homeView/sections/MarketingCollections.ts
  src/schema/v2/homeView/sections/SimilarToRecentlyViewedArtworks.ts
Labels: Art Advisor

#6124 fix: removes @specifiedBy directive from exchange schema
  _schemaV2.graphql
  src/data/exchange.graphql
Labels: Merge On Green

#6123 feat(home view): allow per-env timeout for shows resolver
  src/schema/v2/homeView/helpers/__tests__/withHomeViewTimeout.test.ts
  src/schema/v2/homeView/sections/ShowsForYou.ts
Labels: Art Advisor

#6137 feat: add modern Invoice type, for deprecating Charge
  _schemaV2.graphql
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/schema/v2/Invoice/__tests__/__snapshots__/invoice.test.ts.snap
  src/schema/v2/Invoice/__tests__/createInvoicePayment.test.ts
  src/schema/v2/Invoice/__tests__/invoice.test.ts
  src/schema/v2/Invoice/createInvoicePaymentMutation.ts
  src/schema/v2/Invoice/invoice.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6140 chore: add remainingMinor to Invoice
  _schemaV2.graphql
  src/schema/v2/Invoice/invoice.ts
Labels: Merge On Green

#6122 chore(AMBER-1085): update Commerce Opt in and Opt in Report allow for artsyDomesticShipping param
  _schemaV2.graphql
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
Labels: Jira Synced

#6147 Deploy
  _schemaV2.graphql
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
Labels: Jira Synced

#6150 feat: add improvements for the weaviate mutations
  src/schema/v2/infiniteDiscovery/createDiscoveryUserMutation.ts
  src/schema/v2/infiniteDiscovery/deleteDiscoveryArtworkReferencesMutation.ts
Labels: Squash On Green

#6153 feat(EMI-2098): Add context module to Tasks section in the HomeView
  package.json
  src/schema/v2/homeView/sections/Tasks.ts
  src/schema/v2/homeView/sections/__tests__/Tasks.test.ts
  yarn.lock
Labels: Jira Synced

#6159 fix: use float type instead of int type for certainty
  _schemaV2.graphql
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6164 feat(DIA-863): add tracking to explore and discover home view sections
  package.json
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
  src/schema/v2/homeView/sections/ExploreByCategory.ts
  src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
  src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts
  yarn.lock
Labels: Jira Synced, Squash On Green, Art Advisor

#6174 feat(HomeViewSectionCards): use the OwnerType from analytics in entityType
  src/schema/v2/homeView/sections/ExploreByCategory.ts
Labels: Squash On Green, Art Advisor

#6175 ci(circle): Improve CI times more
  .circleci/config.yml
Labels: performance

#6180 ci(push-schema-changes): trigger schema update to see cycle times
  _schemaV2.graphql
  src/schema/v2/artworks.ts
Labels: Merge On Green

#6190 feat: add isSavedToAnyList to Artwork
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Merge On Green
