Repository artsy/metaphysics, pull requests merged in 2024-06, with the labels that each got.

#5790 feat(partner): Add updatePartnerShow mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/partner/__tests__/updatePartnerShowMutation.test.ts
  src/schema/v2/partner/updatePartnerShowMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#5793 feat(partnerArtist): Add partner artist image support
  _schemaV2.graphql
  src/schema/v2/partner/__tests__/partner_artist.test.js
  src/schema/v2/partner/partner_artist.ts
Labels: Merge On Green

#5794 feat: add includeOnlyTargetSupply param to MyCollectionConnection
  _schemaV2.graphql
  src/schema/v2/me/__tests__/myCollection.test.ts
  src/schema/v2/me/myCollection.ts
Labels: Jira Synced

#5800 chore: AMBER-724 - inquiry sale message
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/edition_set.ts
Labels: Jira Synced, Squash On Green

#5816 chore(AMBER-769): Remove sale message condition checks
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/edition_set.ts
Labels: Jira Synced
