Repository artsy/metaphysics, pull requests merged in 2024-09, with the labels that each got.

#5967 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/__tests__/artworkConsignmentSubmissionType.test.ts
  src/schema/v2/artwork/artworkConsignmentSubmissionType.ts
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/getSectionsForUser.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sections.ts
  src/schema/v2/homeView/zones/__tests__/legacy.test.ts
  src/schema/v2/homeView/zones/legacy.ts
  src/schema/v2/partner/__tests__/partner.test.js
  src/schema/v2/partner/partner.ts
Labels: Jira Synced

#5971 chore: configure alternate ingress host for metaphysics production (DIA-818)
  hokusai/production.yml
Labels: Jira Synced

#5963 feat(onyx-1157): add href and button texts to all home view sections that require it
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewComponent.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/sections.ts
Labels: Art Advisor

#5956 chore(EMI-2049): expose primaryLabel field
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced

#5974 feat(onyx-1217): add withTimeout to home view section resolvers
  src/config.ts
  src/schema/v2/homeView/sections.ts
  src/schema/v2/homeView/withHomeViewTimeout.ts
Labels: Art Advisor

#5980 Deploy
  _schemaV2.graphql
  src/data/specialistBios.json
  src/schema/v2/artist/__tests__/insights.test.ts
  src/schema/v2/artist/helpers.ts
  src/schema/v2/artist/index.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced

#5962 chore: better section names
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sections.ts
Labels: Jira Synced, Art Advisor

#5994 chore: always use sale's database id when querying saleArtworkLoader
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  src/schema/v2/sale/index.ts
Labels: Merge On Green

#5999 chore(EMI-2075): update precedence of collectorSignal.primaryLabel
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced

#6003 chore: misc batched loader updates
  src/lib/loaders/batchSaleArtworkLoader.ts
Labels: Merge On Green

#6001 chore(EMI-2076): add arg to suppress primary labels in collector signals
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced

#6009 refactor(homeView): organize directory structure
  src/schema/v2/homeView/helpers/getSectionsForUser.ts
  src/schema/v2/homeView/helpers/withHomeViewTimeout.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/resolvers/activityResolvers.ts
  src/schema/v2/homeView/resolvers/articlesResolvers.ts
  src/schema/v2/homeView/resolvers/artistResolvers.ts
  src/schema/v2/homeView/resolvers/artworkResolvers.ts
  src/schema/v2/homeView/resolvers/auctionResultsResolvers.ts
  src/schema/v2/homeView/resolvers/featuredFairsResolver.ts
  src/schema/v2/homeView/resolvers/heroUnitsResolvers.ts
  src/schema/v2/homeView/resolvers/marketingCollectionsResolvers.ts
  src/schema/v2/homeView/resolvers/salesResolvers.ts
  src/schema/v2/homeView/sections/index.ts
Labels: Art Advisor

#6013 chore(analytics): add ownerType value to home view viewAll signals
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewComponent.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/sections/index.ts
Labels: Squash On Green, Art Advisor

#6016 feat: add @cacheable directive (experiment) for use in Force CDN caching
  _schemaV2.graphql
  src/directives/cacheableDirective.ts
  src/directives/optionalField/optionalFieldsDirectiveExtension.ts
  src/directives/principalField/__tests__/getPrincipalFieldDirectivePath.test.ts
  src/directives/principalField/__tests__/principalFieldDirectiveValidation.test.ts
  src/directives/principalField/getPrincipalFieldDirectivePath.ts
  src/directives/principalField/principalFieldDirectiveExtension.ts
  src/directives/principalField/principalFieldDirectiveValidation.ts
  src/index.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6017 ci(cloudflare): Add automated deployments
  .circleci/config.yml
  .gitignore
  package.json
  workers/test/ciTestWorker.toml
  workers/test/ciTestWorker.ts
  yarn.lock
Labels: Merge On Green

#6010 refactor(homeView): reorganize section definitions
  src/schema/v2/homeView/resolvers/activityResolvers.ts
  src/schema/v2/homeView/resolvers/articlesResolvers.ts
  src/schema/v2/homeView/resolvers/artistResolvers.ts
  src/schema/v2/homeView/resolvers/artworkResolvers.ts
  src/schema/v2/homeView/resolvers/auctionResultsResolvers.ts
  src/schema/v2/homeView/resolvers/featuredFairsResolver.ts
  src/schema/v2/homeView/resolvers/heroUnitsResolvers.ts
  src/schema/v2/homeView/resolvers/marketingCollectionsResolvers.ts
  src/schema/v2/homeView/resolvers/salesResolvers.ts
  src/schema/v2/homeView/sections/ActiveBids.ts
  src/schema/v2/homeView/sections/AuctionLotsForYou.ts
  src/schema/v2/homeView/sections/Auctions.ts
  src/schema/v2/homeView/sections/CuratorsPicksEmerging.ts
  src/schema/v2/homeView/sections/FeaturedFairs.ts
  src/schema/v2/homeView/sections/GalleriesNearYou.ts
  src/schema/v2/homeView/sections/HeroUnits.ts
  src/schema/v2/homeView/sections/LatestActivity.ts
  src/schema/v2/homeView/sections/LatestArticles.ts
  src/schema/v2/homeView/sections/LatestAuctionResults.ts
  src/schema/v2/homeView/sections/MarketingCollections.ts
  src/schema/v2/homeView/sections/NewWorksForYou.ts
  src/schema/v2/homeView/sections/NewWorksFromGalleriesYouFollow.ts
  src/schema/v2/homeView/sections/News.ts
  src/schema/v2/homeView/sections/RecentlyViewedArtworks.ts
  src/schema/v2/homeView/sections/RecommendedArtists.ts
  src/schema/v2/homeView/sections/RecommendedArtworks.ts
  src/schema/v2/homeView/sections/ShowsForYou.ts
  src/schema/v2/homeView/sections/SimilarToRecentlyViewedArtworks.ts
  src/schema/v2/homeView/sections/TrendingArtists.ts
  src/schema/v2/homeView/sections/ViewingRooms.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/legacy.ts
Labels: Art Advisor

#6019 ci(cloudflare): Add mpcache CloudFlare worker deploy
  .circleci/config.yml
  package.json
  workers/caching/mpcache.toml
  workers/caching/mpcache.ts
Labels: Jira Synced

#6020 Deploy
  .circleci/config.yml
  package.json
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  workers/caching/mpcache.toml
  workers/caching/mpcache.ts
Labels: Jira Synced

#6028 Deploy
  README.md
  docs/cdn.md
  package.json
  src/schema/v2/homeView/sections/RecommendedArtworks.ts
Labels: Jira Synced

#6021 fix(EMI-2093): remove ineligible signals from auction artworks
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
Labels: Jira Synced, Squash On Green

#6034 chore: rename CDN endpoints and workers to metaphysics-cdn*
  README.md
  docs/cdn.md
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  workers/caching/metaphysics-cdn.toml
  workers/caching/metaphysics-cdn.ts
  workers/caching/mpcache.toml
Labels: performance

#6031 Deploy
  .circleci/config.yml
  README.md
  docs/cdn.md
  hokusai/production.yml
  hokusai/staging.yml
  package.json
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/collectorSignals.ts
  workers/caching/metaphysics-cdn.toml
  workers/caching/metaphysics-cdn.ts
  workers/caching/mpcache.toml
Labels: Jira Synced

#6039 chore(AMBER-1019): Create Metaphysics mutation to opt-in artworks
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/partner/CommerceOptIn/CommerceOptInType.ts
  src/schema/v2/partner/CommerceOptIn/__tests__/commerceOptInMutation.test.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6042 feat(homeView): add a feature-flagging pattern for home view sections
  src/lib/featureFlags.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sections/FeaturedFairs.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/legacy.test.ts
  src/schema/v2/homeView/zones/legacy.ts
Labels: Art Advisor

#6047 feat(AMBER-1036): Create mutation to generate artworks eligibility report
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/partner/CommerceOptIn/__tests__/commerceOptInReportMutation.test.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6045 Deploy
  _schemaV2.graphql
  src/data/exchange.graphql
  src/lib/featureFlags.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/Alerts/index.ts
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/__tests__/HomeViewSection.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sections/FeaturedFairs.ts
  src/schema/v2/homeView/sections/_ExampleSection.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/legacy.test.ts
  src/schema/v2/homeView/zones/legacy.ts
  src/schema/v2/partner/CommerceOptIn/__tests__/commerceOptInReportMutation.test.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
  src/schema/v2/partner/__tests__/partner.test.js
  src/schema/v2/partner/partner.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6049 chore: rename legacy zone to default
  src/schema/v2/homeView/helpers/getSectionsForUser.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Art Advisor

#6038 feat: unstitch user devices
  package.json
  src/config.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/devices.ts
  src/schema/v2/user.ts
Labels: Unstitching

#6054 docs: add new display check to ExampleSection
  src/schema/v2/homeView/sections/_ExampleSection.ts
Labels: Merge On Green

#6055 chore: drop type/schema enforcement for home view section contextModule
  _schemaV2.graphql
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/sections/index.ts
Labels: Squash On Green, Art Advisor

#6048 feat: respond to preflight requests from CDN (DIA-889)
  workers/caching/metaphysics-cdn.ts
Labels: performance

#6052 Deploy
  _schemaV2.graphql
  package.json
  src/config.ts
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/lib/loaders/loaders_without_authentication/gravity.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/schema/v2/__tests__/user.test.ts
  src/schema/v2/devices.ts
  src/schema/v2/homeView/HomeViewSection.ts
  src/schema/v2/homeView/helpers/__tests__/isSectionDisplayable.test.ts
  src/schema/v2/homeView/helpers/getSectionsForUser.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/sections/_ExampleSection.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  src/schema/v2/user.ts
  workers/caching/metaphysics-cdn.ts
Labels: Jira Synced

#6056 fix: 'Request header field User-Agent is not allowed by Access-Control-Allow-Headers
  workers/caching/metaphysics-cdn.ts
Labels: Merge On Green

#6061 docs(homeView): amend and simplify example section
  src/schema/v2/homeView/sections/_ExampleSection.ts
Labels: Squash On Green
