Repository artsy/metaphysics, pull requests merged in 2024-01, with the labels that each got.

#5497 feat(EMI-1589): change Artwork#price_listed field type to Money
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#5504 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/Alerts/index.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/me/__tests__/index.test.ts
  src/schema/v2/notifications/Item/PartnerOfferCreatedNotificationItem.ts
  src/schema/v2/notifications/Item/__tests__/index.test.ts
  src/schema/v2/notifications/Item/index.ts
  src/schema/v2/notifications/index.ts
  src/schema/v2/previewSavedSearch/generateDisplayName.ts
Labels: Jira Synced

#5512 feat(H13): Add blurhash field to Image type
  _schemaV2.graphql
  src/schema/v2/image/index.ts
Labels: hackathon

#5516 feat: add lastSavedAt to artwork, new partner artwork connection args
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/partner/partner.ts
  src/schema/v2/sorts/artwork_sorts.ts
  src/types/runtime/gravity/Artwork.ts
Labels: Jira Synced, DO NOT MERGE

#5522 chore: remove savedAtLeastOnce arg from partner.artworksConnection
  _schemaV2.graphql
  src/schema/v2/partner/partner.ts
Labels: Jira Synced

#5526 feat: Add headline field to Notification type
  _schemaV2.graphql
  src/schema/v2/me/__tests__/notification.test.ts
  src/schema/v2/notifications/index.ts
Labels: Jira Synced

#5508 feat(DIA-342): wire up partnerCollectorProfile
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/conversation/__tests__/conversation.test.js
  src/schema/v2/conversation/collectorResume.ts
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#5530 chore(DIA-398): Expose inquiry requests count on collector profile
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
Labels: Jira Synced

#5531 fix(DIA-398): Make inquiry requests count non-nullable
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
Labels: Squash On Green

#5534 chore: rename blurhashDataURI to blurhashDataURL
  _schemaV2.graphql
  src/schema/v2/image/__tests__/index.test.js
  src/schema/v2/image/index.ts
Labels: Merge On Green

#5532 Deploy
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/image/__tests__/index.test.js
  src/schema/v2/image/index.ts
Labels: Jira Synced

#5543 feat: add buyerActivity to collectorResume
  _schemaV2.graphql
  src/lib/stitching/exchange/__tests__/stitching.test.ts
  src/lib/stitching/exchange/v2/stitching.ts
  src/schema/v2/conversation/collectorResume.ts
  src/schema/v2/conversation/index.ts
Labels: Jira Synced

#5547 chore: add internalID and slug to PartialArtwork
  _schemaV2.graphql
  src/schema/v2/artworkResult/__tests__/index.test.ts
  src/schema/v2/artworkResult/index.ts
Labels: Merge On Green

#5546 feat(EMI-1618): return partner on createPartnerOfferMutation
  _schemaV2.graphql
  src/schema/v2/__tests__/createPartnerOfferMutation.test.ts
  src/schema/v2/createPartnerOfferMutation.ts
Labels: Squash On Green
