Repository artsy/metaphysics, pull requests merged in 2025-09, with the labels that each got.

#7066 feat(push-changes): Add artsy-mcp to repo list
  _schemaV2.graphql
  scripts/push-schema-changes.js
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Merge On Green

#7081 fix(yarn): yarn 2+ doesn't support ignore-engines
  scripts/push-schema-changes.js
Labels: Merge On Green

#7084 fix(push-schema): Update destination path for artsy-mcp schema
  scripts/push-schema-changes.js
Labels: Merge On Green

#7065 chore: remove last stiched type from gravity
  _schemaV2.graphql
  package.json
  src/config.ts
  src/lib/stitching/gravity/__tests__/stitching.test.ts
  src/lib/stitching/gravity/__tests__/testingUtils.ts
  src/lib/stitching/gravity/schema.ts
  src/lib/stitching/gravity/v2/stitching.ts
  src/lib/stitching/mergeSchemas.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/userAddress/__tests__/createUserAddressMutation.test.ts
  src/schema/v2/me/userAddress/__tests__/deleteUserAddressMutation.test.ts
  src/schema/v2/me/userAddress/__tests__/updateUserAddressMutation.test.ts
  src/schema/v2/me/userAddress/__tests__/updateUserDefaultAddressMutation.test.ts
  src/schema/v2/me/userAddress/__tests__/userAddressConnection.test.ts
  src/schema/v2/schema.ts
Labels: Unstitching

#7109 chore: remove gravity stitching environment
  src/lib/stitching/gravity/v2/stitching.ts
Labels: Merge On Green

#7115 Deploy
  .circleci/config.yml
  _schemaV2.graphql
  src/schema/v2/CollectorProfile/collectorProfile.ts
  src/schema/v2/me/__tests__/collector_profile.test.js
  src/schema/v2/partner/partner.ts
Labels: Jira Synced

#7124 chore: add collector profile endpoints to non-authenticated loaders
  src/lib/loaders/loaders_without_authentication/gravity.ts
Labels: Jira Synced

#7127 chore: AMBER-2009 - add import source
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced

#7118 fix(DIAM-91): show is displaying different/incorrect dates (using mobile web Artsy)
  src/schema/v2/__tests__/show.test.js
  src/schema/v2/fields/date.ts
Labels: Jira Synced
