Repository artsy/metaphysics, pull requests merged in 2025-05, with the labels that each got.

#6695 chore: add showID to filterArtworksConnection
  _schemaV2.graphql
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#6701 chore: add invalid coa type to import error
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Merge On Green

#6700 Deploy
  _schemaV2.graphql
  src/lib/featureFlags.ts
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/experiments/experiments.ts
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
  src/schema/v2/homeView/sections/ExploreByCategory.ts
  src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
  src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
Labels: Jira Synced

#6694 feat: add Your Bids quick link for users with active bids
  src/schema/v2/homeView/sections/QuickLinks.ts
  src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts
Labels: Squash On Green

#6707 chore: AMBER-1532 - removing incorrect error type
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Squash On Green

#6708 Deploy
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/index.ts
Labels: Jira Synced

#6653 feat(EMI-2208): Rich phone number field for `Order.fulfillmentDetails` type
  _schemaV2.graphql
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/__tests__/updateOrderMutation.test.ts
  src/schema/v2/order/__tests__/updateOrderShippingAddressMutation.test.ts
  src/schema/v2/order/sharedOrderTypes.ts
  src/schema/v2/phoneNumber.ts
Labels: Jira Synced

#6720 fix: remove discover tab from home view running experiments
  src/schema/v2/homeView/experiments/experiments.ts
Labels: Squash On Green

#6714 feat(EMI-2466): Order pricing breakdown lines
  _schemaV2.graphql
  src/lib/moneyHelpers.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/order/MeOrder.ts
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/exchangeErrorHandling.ts
  src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/submitOrderMutation.ts
  src/schema/v2/order/types/PricingBreakdownLines.ts
  src/schema/v2/order/types/exchangeJson.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
  src/schema/v2/order/unsetOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/unsetOrderPaymentMethodMutation.ts
  src/schema/v2/order/updateOrderMutation.ts
  src/schema/v2/order/updateOrderShippingAddressMutation.ts
Labels: Jira Synced

#6719 Deploy
  _schemaV2.graphql
  src/lib/moneyHelpers.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/homeView/experiments/experiments.ts
  src/schema/v2/order/MeOrder.ts
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/__tests__/updateOrderMutation.test.ts
  src/schema/v2/order/exchangeErrorHandling.ts
  src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/sharedOrderTypes.ts
  src/schema/v2/order/submitOrderMutation.ts
  src/schema/v2/order/types/PricingBreakdownLines.ts
  src/schema/v2/order/types/exchangeJson.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
  src/schema/v2/order/unsetOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/unsetOrderPaymentMethodMutation.ts
  src/schema/v2/order/updateOrderMutation.ts
  src/schema/v2/order/updateOrderShippingAddressMutation.ts
Labels: Jira Synced

#6728 fix(DIA-1286): REVERT allow visibility of home view sections to be overridden
  _schemaV2.graphql
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/index.ts
Labels: Jira Synced

#6729 Deploy
  _schemaV2.graphql
  src/lib/featureFlags.ts
  src/schema/v2/artwork/updateArtworkMutation.ts
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/helpers/isSectionDisplayable.ts
  src/schema/v2/homeView/index.ts
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
  src/schema/v2/homeView/sections/ExploreByCategory.ts
  src/schema/v2/homeView/sections/__tests__/DiscoverSomethingNew.test.ts
  src/schema/v2/homeView/sections/__tests__/ExploreByCategory.test.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
Labels: Jira Synced

#6736 chore: AMBER-1615 - adding signature and condition for batch import
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced, Squash On Green

#6724 chore: AMBER-1535 - bulk import signatures
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced, Squash On Green

#6731 feat: expose current user's auction segmentation from Vortex
  _schemaV2.graphql
  src/lib/featureFlags.ts
  src/lib/loaders/loaders_with_authentication/vortex.ts
  src/schema/v2/homeView/mixer/__tests__/rules/AuctionEngagementRule.test.ts
  src/schema/v2/homeView/mixer/rules/AuctionEngagementRule.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  src/schema/v2/me/__tests__/auctionSegmentation.test.ts
  src/schema/v2/me/auctionSegmentation.ts
  src/schema/v2/me/index.ts
Labels: Squash On Green

#6742 fix(EMI-2442): Update Me Order argument type to ID
  _schemaV2.graphql
  src/schema/v2/order/MeOrder.ts
Labels: Jira Synced

#6757 chore: AMBER-1628 - batch import framed dimensions
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced

#6768 feat(EMI-2426): Expose Order payment details
  _schemaV2.graphql
  src/schema/v2/bank_account.ts
  src/schema/v2/credit_card.ts
  src/schema/v2/me/__tests__/credit_cards.test.ts
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/types/exchangeJson.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
Labels: Jira Synced
