Repository artsy/metaphysics, pull requests merged in 2025-01, with the labels that each got.

#6334 feat: update open search artworks index
  _schemaV2.graphql
  src/lib/infiniteDiscovery/findSimilarArtworks.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6336 fix: update query to support new fields
  src/lib/infiniteDiscovery/findSimilarArtworks.ts
Labels: Merge On Green

#6339 chore(AMBER-1116): Enable signature fields to be selected
  _schemaV2.graphql
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
Labels: Jira Synced

#6340 fix: use filter with mlt query
  _schemaV2.graphql
  src/lib/infiniteDiscovery/findSimilarArtworks.ts
Labels: Merge On Green

#6335 Deploy
  _schemaV2.graphql
  scripts/push-schema-changes.js
  src/lib/infiniteDiscovery/findSimilarArtworks.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInMutation.ts
  src/schema/v2/partner/CommerceOptIn/commerceOptInReportMutation.ts
Labels: Jira Synced

#6344 feat: add artworks batch count configurable
  _schemaV2.graphql
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6343 chore(EMI-2226): Add homeViewTasksSection to success response when clearing a task.
  _schemaV2.graphql
  src/schema/v2/homeView/sectionTypes/Tasks.ts
  src/schema/v2/me/__tests__/ack_task_mutation.test.js
  src/schema/v2/me/__tests__/dismiss_task_mutation.test.js
  src/schema/v2/me/ack_task_mutation.ts
  src/schema/v2/me/dismiss_task_mutation.ts
  src/schema/v2/me/task.ts
Labels: Jira Synced

#6359 chore: limit the amount of recommendations
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6371 feat: expose Sale hide_total and total_raised_minor fields
  _schemaV2.graphql
  src/schema/v2/sale/__tests__/index.test.ts
  src/schema/v2/sale/index.ts
Labels: hackathon

#6394 fix: replace meLoader with userId
  src/schema/v2/infiniteDiscovery/__tests__/discoverArtworks.test.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
Labels: Merge On Green

#6383 feat: update shippingInfo logic
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: hackathon
