Repository artsy/metaphysics, pull requests merged in 2025-04, with the labels that each got.

#6587 chore: allow statuses to be passed as an arg to show viewingRoomsConnection
  _schemaV2.graphql
  src/schema/v2/show.ts
Labels: Merge On Green

#6596 chore: tweak timezone handling for mutation input
  src/schema/v2/Show/__tests__/createPartnerShowEventMutation.test.ts
  src/schema/v2/Show/__tests__/updatePartnerShowEventMutation.test.ts
  src/schema/v2/Show/createPartnerShowEventMutation.ts
  src/schema/v2/Show/updatePartnerShowEventMutation.ts
Labels: Merge On Green

#6598 chore: send right unix timestamp back with consideration of timezone
  src/schema/v2/Show/createPartnerShowEventMutation.ts
  src/schema/v2/Show/updatePartnerShowEventMutation.ts
Labels: Merge On Green

#6590 feat(edition-sets): Share fields with sellable
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/artwork/updateArtworkMutation.ts
  src/schema/v2/edition_set.ts
  src/schema/v2/sellable.ts
Labels: Squash On Green

#6599 feat(EMI-2374): create unsetOrderFulfillmentOption mutation + tests
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/exchange.ts
  src/schema/v2/order/__tests__/unsetOrderFulfillmentOptionMutation.test.ts
  src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/unsetOrderFulfillmentOptionMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6608 feat(artwork): add raw diameter field
  _schemaV2.graphql
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#6612 fix: Fix to use the correct endpoint url structure
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Squash On Green

#6616 feat(updateArtwork): Add published input argument
  _schemaV2.graphql
  src/schema/v2/artwork/updateArtworkMutation.ts
Labels: Merge On Green

#6620 fix: Fix `locationId` argument casing
  src/schema/v2/partner/Settings/deletePartnerLocationMutation.ts
Labels: Squash On Green

#6624 feat(filter): Add disableNotForSaleSorting input arg
  _schemaV2.graphql
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#6626 chore: add repositionPartnerArtistArtworks mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/partner/Mutations/PartnerArtist/__tests__/repositionPartnerArtistArtworksMutation.test.ts
  src/schema/v2/partner/Mutations/PartnerArtist/repositionPartnerArtistArtworksMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6628 feat(edition-sets): Expose listPrice for price ranges
  _schemaV2.graphql
  src/lib/stitching/vortex/__tests__/pricingContext.test.ts
  src/schema/v2/fields/listPrice.ts
  src/schema/v2/sellable.ts
Labels: Merge On Green

#6618 feat(EMI-2391): create unsetPaymentMethod mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/exchange.ts
  src/schema/v2/order/__tests__/unsetOrderPaymentMethodMutation.test.ts
  src/schema/v2/order/unsetOrderPaymentMethodMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6630 chore: adding match endpoint for partners
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/match/__tests__/partner.test.js
  src/schema/v2/match/partner.ts
  src/schema/v2/schema.ts
Labels: Squash On Green

#6643 chore: add deletePartnerArtist mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/partner/Mutations/PartnerArtist/__tests__/deletePartnerArtistMutation.test.ts
  src/schema/v2/partner/Mutations/PartnerArtist/deletePartnerArtistMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6644 chore: add biography-related fields to updatePartnerArtist mutation
  _schemaV2.graphql
  src/schema/v2/partner/Mutations/PartnerArtist/updatePartnerArtistMutation.ts
Labels: Merge On Green

#6649 chore: add some more visibility fields to updatePartnerArtist mutation
  _schemaV2.graphql
  src/schema/v2/partner/Mutations/PartnerArtist/updatePartnerArtistMutation.ts
Labels: Merge On Green

#6654 fix(editionSets): Fix type for artistProofs
  _schemaV2.graphql
  src/schema/v2/edition_set.ts
Labels: Merge On Green

#6655 feat(artworksConnection): Thread `artworkIDs` prop through to ES
  _schemaV2.graphql
  src/schema/v2/filterArtworksConnection.ts
Labels: Merge On Green

#6666 chore: AMBER-1530 - adding medium to match its addition in Gravity
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced, Squash On Green

#6667 chore: amber 1530 - bulk import medium invalid
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Squash On Green

#6662 chore: Add mutation to update profiles
  CLAUDE.md
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/profile/__tests__/updateProfileMutation.test.ts
  src/schema/v2/profile/updateProfileMutation.ts
  src/schema/v2/schema.ts
Labels: Squash On Green

#6673 chore: Improve mutation to update partner records
  _schemaV2.graphql
  src/schema/v2/partner/updatePartnerMutation.ts
Labels: Merge On Green

#6677 feat(homeView): introduce HomeViewMixer and use it for for boosting content to new users
  src/lib/featureFlags.ts
  src/schema/v2/homeView/mixer/HomeViewMixer.ts
  src/schema/v2/homeView/mixer/HomeViewMixerRule.ts
  src/schema/v2/homeView/mixer/__tests__/HomeViewMixer.test.ts
  src/schema/v2/homeView/mixer/__tests__/rules/BoostHeroUnitsForNewUsersRule.test.ts
  src/schema/v2/homeView/mixer/rules/BoostHeroUnitsForNewUsersRule.ts
  src/schema/v2/homeView/mixer/rules/DisplayableRule.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Squash On Green

#6691 chore: AMBER-1532 - adding coa
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced
