Repository artsy/metaphysics, pull requests merged in 2025-03, with the labels that each got.

#6482 feat(EMI2297): create exchange json api loaders & MeOrder type
  _schemaV2.graphql
  src/lib/apis/exchange.ts
  src/lib/loaders/api/index.ts
  src/lib/loaders/loaders_with_authentication/exchange.ts
  src/schema/v2/me/index.ts
  src/schema/v2/order/__tests__/order.test.ts
  src/schema/v2/order/fulfillmentOption.ts
  src/schema/v2/order/index.ts
  src/schema/v2/order/lineItem.ts
  yarn.lock
Labels: Jira Synced

#6499 chore: bump minimumEigenVersion for infinite discovery
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
Labels: Merge On Green

#6500 feat(DIA-1194): move infinite discovery above discover something new
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
Labels: Jira Synced, Squash On Green

#6501 fix(DIA-1189): Copy and creative changes to Discover Daily
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
Labels: Jira Synced

#6502 Deploy
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
Labels: Jira Synced

#6509 fix(discover-daily): change entry point button text
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
Labels: Squash On Green

#6506 feat(EMI-2333): New order mutations and building out order type
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/exchange.ts
  src/schema/v2/me/index.ts
  src/schema/v2/me/sendIdentityVerificationEmailMutation.ts
  src/schema/v2/object_identification.ts
  src/schema/v2/order/MeOrder.ts
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/__tests__/setOrderFulfillmentOptionMutation.test.ts
  src/schema/v2/order/__tests__/support.ts
  src/schema/v2/order/__tests__/updateOrderMutation.test.ts
  src/schema/v2/order/fulfillmentOption.ts
  src/schema/v2/order/index.ts
  src/schema/v2/order/lineItem.ts
  src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/sharedTypes.ts
  src/schema/v2/order/updateOrderMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6521 fix(DIA-1236): Update Discover Daily homefeed image to new asset
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
Labels: Jira Synced

#6525 chore: Add sculpture to 3d category list AMBER-1398
  src/schema/v2/artwork/index.ts
Labels: Merge On Green

#6531 fix: place new contacts directory under v2
  src/schema/v2/Contacts/index.ts
  src/schema/v2/partner/partner.ts
Labels: Squash On Green

#6533 chore: add artistsConnection to Show
  _schemaV2.graphql
  src/schema/v2/show.ts
Labels: Merge On Green

#6534 chore: make sure pageCursors available on artworksConnection: Show
  src/schema/v2/show.ts
Labels: Merge On Green

#6536 chore: add eventsConnection to Show
  _schemaV2.graphql
  src/schema/v2/show.ts
  src/schema/v2/show_event.ts
Labels: Merge On Green

#6541 chore: Revert "chore: removes blurhash feature flag"
  src/lib/featureFlags.ts
  src/schema/v2/image/__tests__/index.test.js
  src/schema/v2/image/index.ts
Labels: Squash On Green

#6544 feat: add isFixedShippingFeeOnly property to artwork
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#6545 chore(EMI-2306): Add Order.taxTotal money field
  _schemaV2.graphql
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/sharedOrderTypes.ts
Labels: Jira Synced

#6550 chore: add authenticated partnerShowLoader
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Merge On Green

#6546 Deploy
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/Show/__tests__/createPartnerShowDocumentMutation.test.ts
  src/schema/v2/Show/__tests__/createPartnerShowEventMutation.test.ts
  src/schema/v2/Show/__tests__/createPartnerShowMutation.test.ts
  src/schema/v2/Show/__tests__/deletePartnerShowDocumentMutation.test.ts
  src/schema/v2/Show/__tests__/deletePartnerShowEventMutation.test.ts
  src/schema/v2/Show/__tests__/deletePartnerShowMutation.test.ts
  src/schema/v2/Show/__tests__/updatePartnerShowDocumentMutation.test.ts
  src/schema/v2/Show/__tests__/updatePartnerShowEventMutation.test.ts
  src/schema/v2/Show/__tests__/updatePartnerShowMutation.test.ts
  src/schema/v2/Show/createPartnerShowDocumentMutation.ts
  src/schema/v2/Show/createPartnerShowEventMutation.ts
  src/schema/v2/Show/createPartnerShowMutation.ts
  src/schema/v2/Show/deletePartnerShowDocumentMutation.ts
  src/schema/v2/Show/deletePartnerShowEventMutation.ts
  src/schema/v2/Show/deletePartnerShowMutation.ts
  src/schema/v2/Show/updatePartnerShowDocumentMutation.ts
  src/schema/v2/Show/updatePartnerShowEventMutation.ts
  src/schema/v2/Show/updatePartnerShowMutation.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
  src/schema/v2/fields/money.ts
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/sharedOrderTypes.ts
  src/schema/v2/partner/partnerDocumentsConnection.ts
  src/schema/v2/schema.ts
  src/schema/v2/show_event.ts
Labels: Jira Synced

#6554 chore: correct argument for saving location of a partner show
  src/schema/v2/Show/createPartnerShowMutation.ts
  src/schema/v2/Show/updatePartnerShowMutation.ts
Labels: Merge On Green

#6555 chore: allow nil locations to be set for a partner show
  src/lib/apis/fetch.ts
  src/schema/v2/Show/createPartnerShowMutation.ts
Labels: Merge On Green

#6559 chore: mutation to add install shot to a show
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/Show/__tests__/addInstallShotToPartnerShowMutation.test.ts
  src/schema/v2/Show/addInstallShotToPartnerShowMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6561 chore(EMI-2306): Add tests for Order.taxTotal
  src/schema/v2/order/__tests__/MeOrder.test.ts
Labels: Jira Synced

#6562 chore: remaining install shot mutations
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/Show/__tests__/removeInstallShotFromPartnerShowMutation.test.ts
  src/schema/v2/Show/__tests__/updateInstallShotForPartnerShowMutation.test.ts
  src/schema/v2/Show/removeInstallShotFromPartnerShowMutation.ts
  src/schema/v2/Show/updateInstallShotForPartnerShowMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#6566 fix: correctly handle known errors from exchange
  _schemaV2.graphql
  src/schema/v2/order/__tests__/setOrderFulfillmentOptionMutation.test.ts
  src/schema/v2/order/__tests__/updateOrderMutation.test.ts
  src/schema/v2/order/exchangeErrorHandling.ts
  src/schema/v2/order/setOrderFulfillmentOptionMutation.ts
  src/schema/v2/order/sharedOrderTypes.ts
  src/schema/v2/order/updateOrderMutation.ts
Labels: Jira Synced
