Repository artsy/metaphysics, pull requests merged in 2025-08, with the labels that each got.

#6977 chore(imports): Update delete artwork endpoint
  src/lib/loaders/loaders_with_authentication/gravity.ts
Labels: Merge On Green

#6983 fix: pre-commit schema-v2 updated
  _schemaV2.graphql
Labels: Squash On Green

#6984 feat: add foundations and residencies field to UpdateArtistMutation
  _schemaV2.graphql
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
  src/schema/v2/artist/updateArtistMutation.ts
  src/schema/v2/artwork/__tests__/artwork.test.js
Labels: Merge On Green

#7001 feat: Add image position mutations for artwork imports
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImageMutation.test.ts
  src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImagesMutation.test.ts
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/ArtworkImport/updateArtworkImportRowImageMutation.ts
  src/schema/v2/ArtworkImport/updateArtworkImportRowImagesMutation.ts
  src/schema/v2/schema.ts
Labels: Merge On Green

#7005 Deploy
  _schemaV2.graphql
  package.json
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/ArtworkImport/__tests__/removeArtworkImportImageMutation.test.ts
  src/schema/v2/ArtworkImport/__tests__/updateArtworkImportRowImagesMutation.test.ts
  src/schema/v2/ArtworkImport/removeArtworkImportImageMutation.ts
  src/schema/v2/ArtworkImport/updateArtworkImportRowImagesMutation.ts
  src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
  src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
  yarn.lock
Labels: Merge On Green

#7021 fix(imports): Row id arg should be image level
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/__tests__/matchArtworkImportImagesMutation.test.ts
  src/schema/v2/ArtworkImport/matchArtworkImportImagesMutation.ts
Labels: Merge On Green

#7033 chore: set the default size for UserAddresses
  src/schema/v2/me/userAddress/userAddressesConnection.ts
Labels: Merge On Green

#7040 feat: Support bulk updating signature information
  _schemaV2.graphql
  src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
  src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
Labels: Jira Synced

#7053 chore: AMBER-1779 - adding more free text fields
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced
