Repository artsy/metaphysics, pull requests merged in 2025-06, with the labels that each got.

#6806 chore: use node 22
  .circleci/config.yml
  .nvmrc
  .tool-versions
  Dockerfile
  package.json
  src/lib/__tests__/apis/fetch.test.ts
  src/lib/__tests__/graphqlErrorHandler.test.ts
  src/lib/cache.ts
  src/lib/rateLimiter.ts
  yarn.lock
Labels: Jira Synced

#6807 chore: AMBER-1644 - title validation error
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced

#6831 chore: AMBER-1682 - adding blocking attribute per row error
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced, Squash On Green

#6840 feat(DIA-1363): guarantee non-null discoveryMarketingCollections results
  _schemaV2.graphql
  src/schema/v2/__tests__/marketingCollections.test.ts
  src/schema/v2/marketingCollections.ts
Labels: Squash On Green

#6852 fix(EMI-2448): propagate exchange processing errors from submit mutation
  _schemaV2.graphql
  src/schema/v2/order/__tests__/submitOrderMutation.test.ts
  src/schema/v2/order/exchangeErrorHandling.ts
  src/schema/v2/order/submitOrderMutation.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
Labels: Jira Synced

#6859 chore: AMBER-1688 - remove artwork import preferences
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/ArtworkImport/__tests__/updateArtworkImportMutation.test.ts
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/ArtworkImport/createArtworkImportMutation.ts
  src/schema/v2/ArtworkImport/updateArtworkImportMutation.ts
  src/schema/v2/schema.ts
Labels: Jira Synced, Squash On Green

#6864 chore: AMBER-1735 - artwork import preferences
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Jira Synced, Squash On Green
