Repository artsy/metaphysics, pull requests merged in 2025-02, with the labels that each got.

#6354 feat(ONYX-1479): add quick links section
  _schemaV2.graphql
  package.json
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/sectionTypes/NavigationPills.ts
  src/schema/v2/homeView/sectionTypes/index.ts
  src/schema/v2/homeView/sectionTypes/names.ts
  src/schema/v2/homeView/sections/QuickLinks.ts
  src/schema/v2/homeView/sections/__tests__/QuickLinks.test.ts
  src/schema/v2/homeView/sections/index.ts
  src/schema/v2/homeView/zones/__tests__/default.test.ts
  src/schema/v2/homeView/zones/default.ts
  yarn.lock
Labels: Squash On Green

#6399 chore(ONYX-1511): rename alleries section title
  src/schema/v2/homeView/__tests__/HomeView.test.ts
  src/schema/v2/homeView/sections/GalleriesNearYou.ts
  src/schema/v2/homeView/sections/__tests__/GalleriesNearYou.test.ts
Labels: Jira Synced

#6412 chore: add artwork framed dimensions and weight.
  _schemaV2.graphql
  src/schema/v2/artwork/__tests__/artwork.test.js
  src/schema/v2/artwork/index.ts
Labels: Jira Synced

#6425 chore: add badgeText to card
  _schemaV2.graphql
  src/schema/v2/homeView/sectionTypes/Card.ts
  src/schema/v2/homeView/sections/InfiniteDiscovery.ts
  src/schema/v2/homeView/sections/__tests__/InfiniteDiscovery.test.ts
Labels: Jira Synced

#6434 feat(DIA-990): Switching out marketing collections in Discover Something New
  src/schema/v2/homeView/sections/DiscoverSomethingNew.ts
Labels: Jira Synced

#6442 chore: drop rowID argument from matching an image to an import by filename
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/__tests__/matchArtworkImportRowImageMutation.test.ts
  src/schema/v2/ArtworkImport/matchArtworkImportRowImageMutation.ts
Labels: Merge On Green

#6443 feat: add user seen artworks mutation
  _schemaV2.graphql
  src/lib/loaders/loaders_with_authentication/gravity.ts
  src/schema/v2/infiniteDiscovery/__tests__/discoverArtworks.test.ts
  src/schema/v2/infiniteDiscovery/createUserSeenArtworkMutation.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
  src/schema/v2/schema.ts
Labels: Jira Synced

#6463 feat(AMBER-1304): Expose category and price fields for Batch Edits
  _schemaV2.graphql
  src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
Labels: Jira Synced

#6464 Deploy
  _schemaV2.graphql
  src/config.ts
  src/schema/v2/ArtworkImport/artworkImport.ts
  src/schema/v2/infiniteDiscovery/discoverArtworks.ts
  src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
Labels: Jira Synced

#6475 chore: AMBER-1316 - artwork imports list page
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Squash On Green

#6479 chore: adding new artwork import rows parameter
  _schemaV2.graphql
  src/schema/v2/ArtworkImport/artworkImport.ts
Labels: Squash On Green
