Repository artsy/metaphysics, pull requests merged in 2025-07, with the labels that each got.

#6872 feat: add trackItemImpressions to HomeViewSectionArtworks
  _schemaV2.graphql
  src/schema/v2/homeView/sectionTypes/Artworks.ts
  src/schema/v2/homeView/sectionTypes/_ExampleSectionType.ts
  src/schema/v2/homeView/sections/NewWorksForYou.ts
  src/schema/v2/homeView/sections/_ExampleSection.ts
  src/schema/v2/homeView/sections/__tests__/NewWorksForYou.test.ts
Labels: Jira Synced, Squash On Green

#6893 fix: missing italics in artist bio credit line
  src/schema/v2/artist/__tests__/index.test.js
  src/schema/v2/artist/index.ts
Labels: Squash On Green

#6924 revert: partially revert change to untether convection
  src/config.ts
  src/schema/v2/system/services/convection.ts
Labels: Squash On Green

#6926 feat: add foundations fair url for 2025
  src/schema/v2/artist/helpers.ts
Labels: Merge On Green

#6932 fix: correcting signature property name for bulk-update
  _schemaV2.graphql
  src/schema/v2/partner/BulkOperation/__tests__/bulkUpdateArtworksMetadataMutation.test.ts
  src/schema/v2/partner/BulkOperation/bulkUpdateArtworksMetadataMutation.ts
Labels: Jira Synced

#6934 Deploy
  _schemaV2.graphql
  src/schema/v2/order/__tests__/submitOrderMutation.test.ts
  src/schema/v2/order/exchangeErrorHandling.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
Labels: Jira Synced

#6936 feat(EMI-2506): add Order.availablePaymentMethods field
  _schemaV2.graphql
  src/schema/v2/order/__tests__/MeOrder.test.ts
  src/schema/v2/order/types/exchangeJson.ts
  src/schema/v2/order/types/sharedOrderTypes.ts
Labels: Jira Synced

#6950 chore: ignore .claude/settings.local.json folder
  .gitignore
Labels: Merge On Green

#6963 revert: "feat(EMI-2674): add a type field to the confirmationToken query"
  _schemaV2.graphql
  src/schema/v2/order/__tests__/confirmationToken.test.ts
  src/schema/v2/order/confirmationToken.ts
Labels: Jira Synced
